/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.imobiliaria.views;

import javax.swing.table.DefaultTableModel;

import com.mycompany.imobiliaria.controllers.PaymentController;
import com.mycompany.imobiliaria.controllers.RentalController;
import com.mycompany.imobiliaria.controllers.RealEstateController;
import com.mycompany.imobiliaria.models.PaymentModel;
import com.mycompany.imobiliaria.models.RentalModel;
import com.mycompany.imobiliaria.models.RealEstateModel;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.PDFRenderer;

/**
 *
 * @author user
 */
public class PaymentRegister extends javax.swing.JFrame {
    private static final PaymentController paymentController = new PaymentController();
    private RentalModel rental;
    private PaymentModel selectedPayment;
    private CardLayout paymentCardLayout;
    private Image receiptImage;
    private double receiptImageScale = 1.0;
    
    /**
     * Creates new form PaymentRegister
     */
    public PaymentRegister(int rentalId) {
        initComponents();
        
        this.paymentCardLayout = ((CardLayout) paymentPanel.getLayout());
        
        setLayout(null);
        backgroundLabel.setBounds(0, 0, getWidth(), getHeight());
        
        RentalController rentalController = new RentalController();   
        this.rental = rentalController.getRentalById(rentalId);
        
        RealEstateController realEstateController = new RealEstateController();   
        RealEstateModel property = realEstateController.getPropertyById(this.rental.getPropertyId());
        
        String address = property.getAddress() + ", " + property.getNumber() + "\n" + 
                property.getNeighborhood() + " - " + property.getCity();;
        addressTextArea.setText(address);
        
        this.updateTable();
    }
    
    private void updateTable() {
        DefaultTableModel tableModel = (DefaultTableModel) paymentTable.getModel();
        tableModel.setRowCount(0);
            
        for (PaymentModel payment : paymentController.getAllPayments(this.rental.getId())) {
            String paymentDate = String.format(
                "%02d/%02d/%04d", 
                payment.getPayment_day(), 
                payment.getPayment_month(), 
                payment.getPayment_year()
            );
            
            String referenceDate = String.format(
                "%02d/%04d", 
                payment.getReference_month(), 
                payment.getReference_year()
            );

            
            Object[] row = {
                payment.getId(),
                paymentDate,
                referenceDate,
            };
            tableModel.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        paymentScrollPanel = new javax.swing.JScrollPane();
        paymentTable = new javax.swing.JTable();
        paymentPanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        realEstatePanel = new javax.swing.JPanel();
        addressTextArea = new javax.swing.JTextArea();
        paymentFormPanel = new javax.swing.JPanel();
        paymentTitlePanel = new javax.swing.JPanel();
        paymentTitleLabel = new javax.swing.JLabel();
        paymentDateTextField = new javax.swing.JFormattedTextField();
        paymentMenuPanel = new javax.swing.JPanel();
        registerButton = new javax.swing.JButton();
        contractPanel = new javax.swing.JPanel();
        contractButton = new javax.swing.JButton();
        receiptImagePanel = new javax.swing.JPanel();
        receiptImageScrollPanel = new javax.swing.JScrollPane();
        receiptImageLabel = new javax.swing.JLabel();
        receiptMenuPanel = new javax.swing.JPanel();
        lessZoomButton = new javax.swing.JButton();
        moreZoomButton = new javax.swing.JButton();
        menuPanel = new javax.swing.JPanel();
        returnButton = new javax.swing.JButton();
        changeButton = new javax.swing.JButton();
        downloadButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pagamentos");
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setMaximumSize(new java.awt.Dimension(800, 500));
        backgroundPanel.setMinimumSize(new java.awt.Dimension(800, 500));
        backgroundPanel.setName(""); // NOI18N
        backgroundPanel.setPreferredSize(new java.awt.Dimension(800, 500));
        backgroundPanel.setBackground(new java.awt.Color(40, 40, 40, 160));
        backgroundPanel.setBorder(null);
        backgroundPanel.setLayout(new javax.swing.BoxLayout(backgroundPanel, javax.swing.BoxLayout.LINE_AXIS));

        paymentScrollPanel.setMaximumSize(new java.awt.Dimension(400, 500));
        paymentScrollPanel.setMinimumSize(new java.awt.Dimension(400, 500));
        paymentScrollPanel.setPreferredSize(new java.awt.Dimension(400, 500));
        paymentScrollPanel.setOpaque(false);
        paymentScrollPanel.getViewport().setBackground(new java.awt.Color(40, 40, 40, 180));
        paymentScrollPanel.getViewport().setBorder(null);

        paymentTable.setOpaque(false);
        ((DefaultTableCellRenderer) paymentTable.getDefaultRenderer(Object.class)).setBackground(new java.awt.Color(120, 120, 160, 180));
        ((DefaultTableCellRenderer) paymentTable.getDefaultRenderer(Object.class)).setBorder(null);
        paymentTable.getTableHeader().setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        paymentTable.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        paymentTable.getTableHeader().setBackground(new java.awt.Color(40, 40, 80, 255));
        paymentTable.getTableHeader().setBorder(null);
        paymentTable.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        paymentTable.setForeground(new java.awt.Color(255, 255, 255));
        paymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Pagament", "Referência"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        paymentTable.setMaximumSize(new java.awt.Dimension(400, 500));
        paymentTable.setMinimumSize(new java.awt.Dimension(400, 500));
        paymentTable.setPreferredSize(new java.awt.Dimension(400, 500));
        paymentTable.setRowHeight(25);
        paymentScrollPanel.setViewportView(paymentTable);
        if (paymentTable.getColumnModel().getColumnCount() > 0) {
            paymentTable.getColumnModel().getColumn(0).setPreferredWidth(40);
        }

        backgroundPanel.add(paymentScrollPanel);

        paymentPanel.setMaximumSize(new java.awt.Dimension(400, 500));
        paymentPanel.setMinimumSize(new java.awt.Dimension(400, 500));
        paymentPanel.setOpaque(false);
        paymentPanel.setPreferredSize(new java.awt.Dimension(400, 500));
        paymentPanel.setLayout(new java.awt.CardLayout());

        formPanel.setOpaque(false);
        formPanel.setLayout(new java.awt.GridLayout(2, 0));

        realEstatePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        realEstatePanel.setMaximumSize(new java.awt.Dimension(300, 200));
        realEstatePanel.setMinimumSize(new java.awt.Dimension(300, 100));
        realEstatePanel.setOpaque(false);
        realEstatePanel.setPreferredSize(new java.awt.Dimension(300, 100));
        realEstatePanel.setLayout(new javax.swing.BoxLayout(realEstatePanel, javax.swing.BoxLayout.PAGE_AXIS));

        addressTextArea.setEditable(false);
        addressTextArea.setColumns(5);
        addressTextArea.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        addressTextArea.setForeground(new java.awt.Color(255, 255, 255));
        addressTextArea.setLineWrap(true);
        addressTextArea.setRows(4);
        addressTextArea.setText("Rua São João Benedito das Areias Cristalinas, 758\n");
        addressTextArea.setWrapStyleWord(true);
        addressTextArea.setAutoscrolls(false);
        addressTextArea.setFocusable(false);
        addressTextArea.setMaximumSize(new java.awt.Dimension(250, 100));
        addressTextArea.setMinimumSize(new java.awt.Dimension(250, 40));
        addressTextArea.setOpaque(false);
        realEstatePanel.add(addressTextArea);

        formPanel.add(realEstatePanel);

        paymentFormPanel.setOpaque(false);
        paymentFormPanel.setLayout(new javax.swing.BoxLayout(paymentFormPanel, javax.swing.BoxLayout.PAGE_AXIS));

        paymentTitlePanel.setMaximumSize(new java.awt.Dimension(10000, 30));
        paymentTitlePanel.setMinimumSize(new java.awt.Dimension(100, 30));
        paymentTitlePanel.setOpaque(false);
        paymentTitlePanel.setPreferredSize(new java.awt.Dimension(100, 30));

        paymentTitleLabel.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        paymentTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        paymentTitleLabel.setText("Novo Pagamento");
        paymentTitlePanel.add(paymentTitleLabel);

        paymentFormPanel.add(paymentTitlePanel);

        paymentDateTextField.setBackground(new java.awt.Color(120, 120, 120));
        paymentDateTextField.setForeground(new java.awt.Color(255, 255, 255));
        try {
            paymentDateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        paymentDateTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        paymentDateTextField.setMaximumSize(new java.awt.Dimension(250, 30));
        paymentDateTextField.setMinimumSize(new java.awt.Dimension(250, 30));
        paymentDateTextField.setName(""); // NOI18N
        paymentDateTextField.setPreferredSize(new java.awt.Dimension(250, 30));
        paymentFormPanel.add(paymentDateTextField);

        paymentMenuPanel.setOpaque(false);

        registerButton.setBackground(new java.awt.Color(40, 40, 80));
        registerButton.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Cadastrar");
        registerButton.setMaximumSize(new java.awt.Dimension(150, 30));
        registerButton.setMinimumSize(new java.awt.Dimension(150, 30));
        registerButton.setPreferredSize(new java.awt.Dimension(150, 30));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        paymentMenuPanel.add(registerButton);

        paymentFormPanel.add(paymentMenuPanel);

        contractPanel.setOpaque(false);

        contractButton.setBackground(new java.awt.Color(40, 40, 80));
        contractButton.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        contractButton.setForeground(new java.awt.Color(255, 255, 255));
        contractButton.setText("Contrato");
        contractButton.setMaximumSize(new java.awt.Dimension(150, 30));
        contractButton.setMinimumSize(new java.awt.Dimension(150, 30));
        contractButton.setPreferredSize(new java.awt.Dimension(150, 30));
        contractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contractButtonActionPerformed(evt);
            }
        });
        contractPanel.add(contractButton);

        paymentFormPanel.add(contractPanel);

        formPanel.add(paymentFormPanel);

        paymentPanel.add(formPanel, "paymentForm");

        receiptImagePanel.setMaximumSize(new java.awt.Dimension(300, 400));
        receiptImagePanel.setMinimumSize(new java.awt.Dimension(300, 400));
        receiptImagePanel.setOpaque(false);
        receiptImagePanel.setPreferredSize(new java.awt.Dimension(300, 400));
        receiptImagePanel.setLayout(new javax.swing.BoxLayout(receiptImagePanel, javax.swing.BoxLayout.PAGE_AXIS));

        receiptImageScrollPanel.setMaximumSize(new java.awt.Dimension(400, 350));
        receiptImageScrollPanel.setMinimumSize(new java.awt.Dimension(400, 350));
        receiptImageScrollPanel.setPreferredSize(new java.awt.Dimension(400, 350));
        receiptImageScrollPanel.setViewportView(receiptImageLabel);

        receiptImagePanel.add(receiptImageScrollPanel);

        receiptMenuPanel.setMaximumSize(new java.awt.Dimension(32767, 50));
        receiptMenuPanel.setMinimumSize(new java.awt.Dimension(167, 50));
        receiptMenuPanel.setOpaque(false);
        receiptMenuPanel.setPreferredSize(new java.awt.Dimension(100, 50));

        lessZoomButton.setToolTipText("Menos zoom");
        ImageIcon lessZoomIcon = new ImageIcon(getClass().getResource("/static/icons/less-glass.png"));
        lessZoomButton.setIcon(lessZoomIcon);
        lessZoomButton.setText("");
        lessZoomButton.setHorizontalAlignment(SwingConstants.CENTER);
        lessZoomButton.setBorderPainted(false);
        lessZoomButton.setContentAreaFilled(false);
        lessZoomButton.setBorderPainted(true);
        lessZoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lessZoomButtonActionPerformed(evt);
            }
        });
        receiptMenuPanel.add(lessZoomButton);

        moreZoomButton.setToolTipText("Mais zoom");
        ImageIcon moreZoomIcon = new ImageIcon(getClass().getResource("/static/icons/more-glass.png"));
        moreZoomButton.setIcon(moreZoomIcon);
        moreZoomButton.setText("");
        moreZoomButton.setHorizontalAlignment(SwingConstants.CENTER);
        moreZoomButton.setBorderPainted(false);
        moreZoomButton.setContentAreaFilled(false);
        moreZoomButton.setBorderPainted(true);
        moreZoomButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moreZoomButtonActionPerformed(evt);
            }
        });
        receiptMenuPanel.add(moreZoomButton);

        receiptImagePanel.add(receiptMenuPanel);

        menuPanel.setMaximumSize(new java.awt.Dimension(400, 50));
        menuPanel.setMinimumSize(new java.awt.Dimension(400, 50));
        menuPanel.setOpaque(false);
        menuPanel.setPreferredSize(new java.awt.Dimension(400, 50));

        returnButton.setBackground(new java.awt.Color(40, 40, 80));
        returnButton.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        returnButton.setForeground(new java.awt.Color(255, 255, 255));
        returnButton.setText("Voltar");
        returnButton.setMaximumSize(new java.awt.Dimension(100, 30));
        returnButton.setMinimumSize(new java.awt.Dimension(100, 30));
        returnButton.setPreferredSize(new java.awt.Dimension(100, 30));
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        menuPanel.add(returnButton);

        changeButton.setBackground(new java.awt.Color(40, 40, 80));
        changeButton.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        changeButton.setForeground(new java.awt.Color(255, 255, 255));
        changeButton.setText("Substituir");
        changeButton.setMaximumSize(new java.awt.Dimension(100, 30));
        changeButton.setMinimumSize(new java.awt.Dimension(100, 30));
        changeButton.setPreferredSize(new java.awt.Dimension(100, 30));
        changeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeButtonActionPerformed(evt);
            }
        });
        menuPanel.add(changeButton);

        downloadButton.setBackground(new java.awt.Color(40, 40, 80));
        downloadButton.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        downloadButton.setForeground(new java.awt.Color(255, 255, 255));
        downloadButton.setText("Download");
        downloadButton.setMaximumSize(new java.awt.Dimension(100, 30));
        downloadButton.setMinimumSize(new java.awt.Dimension(100, 30));
        downloadButton.setPreferredSize(new java.awt.Dimension(100, 30));
        downloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButtonActionPerformed(evt);
            }
        });
        menuPanel.add(downloadButton);

        receiptImagePanel.add(menuPanel);

        paymentPanel.add(receiptImagePanel, "paymentReceipt");

        backgroundPanel.add(paymentPanel);

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        Image backgroundImage = new ImageIcon(getClass().getResource("/static/icons/background.png")).getImage();
        Image scaledImage = backgroundImage.getScaledInstance(getWidth(), getHeight(), Image.SCALE_SMOOTH);
        backgroundLabel.setIcon(new ImageIcon(scaledImage));
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String date = paymentDateTextField.getText();
        
        if ("  /  /    ".equals(date)) {
            JOptionPane.showMessageDialog(null, "Insira uma data de pagamento válida");
            return;
        }

        String[] paymentDate = date.split("/");

        List<PaymentModel> payments = paymentController.getAllPayments(rental.getId());
        
        int referenceMonth;
        int referenceYear;
        
        if (payments.isEmpty()) {
            referenceMonth = rental.getContractMonth() + 1;
            referenceYear = rental.getContractYear();
            
            if (referenceMonth > 12) {
                referenceMonth = 1;
                referenceYear += 1;
            }
        } else {
            PaymentModel lastPayment = payments.get(0);
            
            referenceMonth = lastPayment.getReference_month() + 1;
            referenceYear = lastPayment.getReference_year();
            
            if (referenceMonth > 12) {
                referenceMonth = 1;
                referenceYear += 1;
            }
        }
        
        PaymentModel payment = new PaymentModel(
                Integer.parseInt(paymentDate[0]),
                Integer.parseInt(paymentDate[1]),
                Integer.parseInt(paymentDate[2]),
                referenceMonth,
                referenceYear,
                rental.getId(),
                ""
            );
            
        paymentController.addPayment(payment);
        JOptionPane.showMessageDialog(null, "Pagamento cadastrado com sucesso");
        
        this.updateTable();
        paymentDateTextField.setText("");
    }//GEN-LAST:event_registerButtonActionPerformed

    private void contractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contractButtonActionPerformed
        int row = paymentTable.getSelectedRow();
        if (row == -1) return;
        
        String id = String.valueOf(paymentTable.getValueAt(row, 0));
        
        selectedPayment = paymentController.getPaymentById(Integer.parseInt(id));
        
        if (selectedPayment.getContract() == null) {
            this.addDocument(id);
        } else {
            this.paymentCardLayout.show(paymentPanel, "paymentReceipt");
            this.loadReceipt(selectedPayment.getContract());
        }
    }//GEN-LAST:event_contractButtonActionPerformed

    private void lessZoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lessZoomButtonActionPerformed
        this.receiptImageScale -= 0.25;
        this.plotImage();
    }//GEN-LAST:event_lessZoomButtonActionPerformed

    private void moreZoomButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moreZoomButtonActionPerformed
        this.receiptImageScale += 0.25;
        this.plotImage();
    }//GEN-LAST:event_moreZoomButtonActionPerformed

    private void changeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeButtonActionPerformed
        this.addDocument(String.valueOf(selectedPayment.getId()));
        selectedPayment = paymentController.getPaymentById(selectedPayment.getId());
        this.loadReceipt(selectedPayment.getContract());
    }//GEN-LAST:event_changeButtonActionPerformed

    private void downloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadButtonActionPerformed
        if (selectedPayment.getContract() == null) return;

        String extention = getFileExtension(selectedPayment.getContract());

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Onde deseja salvar o arquivo?");
        fileChooser.setSelectedFile(new File("recibo." + extention));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File saveFile = fileChooser.getSelectedFile();
            try {
                Files.copy(new File(selectedPayment.getContract()).toPath(), saveFile.toPath());
                JOptionPane.showMessageDialog(this, "Recibo baixado com sucesso.");
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_downloadButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        this.paymentCardLayout.show(paymentPanel, "paymentForm");
    }//GEN-LAST:event_returnButtonActionPerformed

    public void addDocument(String id) {
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            
            String extension = getFileExtension(selectedFile.getName());
  
            File internalStorage = new File("internal_storage/receipts");
            if (!internalStorage.exists()) {
                internalStorage.mkdirs();
            }
            
            File destFile = new File(internalStorage, id + "." + extension);

            try (InputStream in = new FileInputStream(selectedFile);
                 OutputStream out = new FileOutputStream(destFile)) {

                byte[] buffer = new byte[1024];
                int length;
                while ((length = in.read(buffer)) > 0) {
                    out.write(buffer, 0, length);
                }
                
                paymentController.addReceipt(Integer.parseInt(id), destFile.getAbsolutePath());
                JOptionPane.showMessageDialog(null, "Recibo salvo com sucesso");
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }
    
    public void loadReceipt(String contractPath) {
        String extension = getFileExtension(contractPath).toLowerCase();
        
        switch (extension) {
            case "jpg":
            case "jpeg":
            case "png":
                this.receiptImage = new ImageIcon(contractPath).getImage();
                break;
            case "pdf":
                try {
                    File file = new File(contractPath);
                    PDDocument document = PDDocument.load(file);
                    PDFRenderer renderer = new PDFRenderer(document);

                    int numPages = document.getNumberOfPages();
                    int dpi = 150;

                    List<BufferedImage> contractPages = new ArrayList<>();
                    int totalHeight = 0;
                    int width = 0;
                    int separatorHeight = 5;

                    for (int pageIndex = 0; pageIndex < numPages; pageIndex++) {
                        contractPages.add(renderer.renderImageWithDPI(pageIndex, dpi));

                        totalHeight += contractPages.get(pageIndex).getHeight();
                        if (pageIndex != numPages - 1) {
                            totalHeight += separatorHeight;
                        }

                        width = Math.max(width, contractPages.get(pageIndex).getWidth());
                    }
                    
                    BufferedImage fullContractImage = new BufferedImage(width, totalHeight, BufferedImage.TYPE_INT_RGB);
                    Graphics2D g2d = fullContractImage.createGraphics();

                    g2d.setColor(Color.WHITE);
                    g2d.fillRect(0, 0, width, totalHeight);

                    int y = 0;
                    for (int i = 0; i < contractPages.size(); i++) {
                        BufferedImage page = contractPages.get(i);
                        g2d.drawImage(page, 0, y, null);
                        y += page.getHeight();

                        if (i != contractPages.size() - 1) {
                            g2d.setColor(Color.BLACK);
                            g2d.fillRect(0, y, width, separatorHeight);
                            y += separatorHeight;
                        }
                    }
                    
                    g2d.dispose();
                    document.close();

                    this.receiptImage = fullContractImage;
                } catch (Exception ex) {
                    ex.printStackTrace();
                    this.receiptImage = new ImageIcon(getClass().getResource("/static/icons/documentNotSupported.png")).getImage();
                }
                break;
            default:
                this.receiptImage = new ImageIcon(getClass().getResource("/static/icons/documentNotSupported.png")).getImage();
                break;
        }
        plotImage();
    }
    
    public void plotImage() {
        int width = (int) (this.receiptImage.getWidth(null) * this.receiptImageScale);
        int height = (int) (this.receiptImage.getHeight(null) * this.receiptImageScale);
        Image scaledImage = this.receiptImage.getScaledInstance(width, height, Image.SCALE_SMOOTH);
        receiptImageLabel.setIcon(new ImageIcon(scaledImage));
    }
    
    public String getFileExtension(String filePath) {
        int dotIndex = filePath.lastIndexOf('.');
        return (dotIndex == -1) ? "" : filePath.substring(dotIndex + 1);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(int rentalId, String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentRegister(rentalId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton changeButton;
    private javax.swing.JButton contractButton;
    private javax.swing.JPanel contractPanel;
    private javax.swing.JButton downloadButton;
    private javax.swing.JPanel formPanel;
    private javax.swing.JButton lessZoomButton;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JButton moreZoomButton;
    private javax.swing.JFormattedTextField paymentDateTextField;
    private javax.swing.JPanel paymentFormPanel;
    private javax.swing.JPanel paymentMenuPanel;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JScrollPane paymentScrollPanel;
    private javax.swing.JTable paymentTable;
    private javax.swing.JLabel paymentTitleLabel;
    private javax.swing.JPanel paymentTitlePanel;
    private javax.swing.JPanel realEstatePanel;
    private javax.swing.JLabel receiptImageLabel;
    private javax.swing.JPanel receiptImagePanel;
    private javax.swing.JScrollPane receiptImageScrollPanel;
    private javax.swing.JPanel receiptMenuPanel;
    private javax.swing.JButton registerButton;
    private javax.swing.JButton returnButton;
    // End of variables declaration//GEN-END:variables
}
