/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.imobiliaria.views;

import javax.swing.table.DefaultTableModel;

import com.mycompany.imobiliaria.controllers.PaymentController;
import com.mycompany.imobiliaria.controllers.RentalController;
import com.mycompany.imobiliaria.controllers.RealEstateController;
import com.mycompany.imobiliaria.models.PaymentModel;
import com.mycompany.imobiliaria.models.RentalModel;
import com.mycompany.imobiliaria.models.RealEstateModel;
import java.awt.CardLayout;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author user
 */
public class PaymentRegister extends javax.swing.JFrame {
    private static final PaymentController paymentController = new PaymentController();
    private RentalModel rental;
    private PaymentModel selectedPayment;
    private CardLayout paymentCardLayout;
    
    /**
     * Creates new form PaymentRegister
     */
    public PaymentRegister(int rentalId) {
        initComponents();
        
        this.paymentCardLayout = ((CardLayout) paymentPanel.getLayout());
        
        setLayout(null);
        backgroundLabel.setBounds(0, 0, getWidth(), getHeight());
        
        RentalController rentalController = new RentalController();   
        this.rental = rentalController.getRentalById(rentalId);
        
        RealEstateController realEstateController = new RealEstateController();   
        RealEstateModel property = realEstateController.getPropertyById(this.rental.getPropertyId());
        
        String address = property.getAddress() + ", " + property.getNumber() + "\n" + 
                property.getNeighborhood() + " - " + property.getCity();;
        addressTextArea.setText(address);
        
        this.updateTable();
    }
    
    private void updateTable() {
        DefaultTableModel tableModel = (DefaultTableModel) paymentTable.getModel();
        tableModel.setRowCount(0);
            
        for (PaymentModel payment : paymentController.getAllPayments(this.rental.getId())) {
            String paymentDate = String.format(
                "%02d/%02d/%04d", 
                payment.getPayment_day(), 
                payment.getPayment_month(), 
                payment.getPayment_year()
            );
            
            String referenceDate = String.format(
                "%02d/%04d", 
                payment.getReference_month(), 
                payment.getReference_year()
            );

            
            Object[] row = {
                payment.getId(),
                paymentDate,
                referenceDate,
            };
            tableModel.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        paymentScrollPanel = new javax.swing.JScrollPane();
        paymentTable = new javax.swing.JTable();
        paymentPanel = new javax.swing.JPanel();
        formPanel = new javax.swing.JPanel();
        realEstatePanel = new javax.swing.JPanel();
        addressTextArea = new javax.swing.JTextArea();
        paymentFormPanel = new javax.swing.JPanel();
        paymentTitlePanel = new javax.swing.JPanel();
        paymentTitleLabel = new javax.swing.JLabel();
        paymentDateTextField = new javax.swing.JFormattedTextField();
        paymentMenuPanel = new javax.swing.JPanel();
        registerButton = new javax.swing.JButton();
        contractPanel = new javax.swing.JPanel();
        contractButton = new javax.swing.JButton();
        ContractImagePanel = new javax.swing.JPanel();
        contractImageScrollPanel = new javax.swing.JScrollPane();
        contractImageLabel = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pagamentos");
        setMaximumSize(new java.awt.Dimension(700, 400));
        setMinimumSize(new java.awt.Dimension(700, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setMaximumSize(new java.awt.Dimension(700, 400));
        backgroundPanel.setMinimumSize(new java.awt.Dimension(700, 400));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(700, 400));
        backgroundPanel.setBackground(new java.awt.Color(40, 40, 40, 160));
        backgroundPanel.setBorder(null);
        backgroundPanel.setLayout(new javax.swing.BoxLayout(backgroundPanel, javax.swing.BoxLayout.LINE_AXIS));

        paymentScrollPanel.setOpaque(false);
        paymentScrollPanel.getViewport().setBackground(new java.awt.Color(40, 40, 40, 180));
        paymentScrollPanel.getViewport().setBorder(null);

        paymentTable.setOpaque(false);
        ((DefaultTableCellRenderer) paymentTable.getDefaultRenderer(Object.class)).setBackground(new java.awt.Color(120, 120, 160, 180));
        ((DefaultTableCellRenderer) paymentTable.getDefaultRenderer(Object.class)).setBorder(null);
        paymentTable.getTableHeader().setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        paymentTable.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        paymentTable.getTableHeader().setBackground(new java.awt.Color(40, 40, 80, 255));
        paymentTable.getTableHeader().setBorder(null);
        paymentTable.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        paymentTable.setForeground(new java.awt.Color(255, 255, 255));
        paymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Pagament", "Referência"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        paymentTable.setMaximumSize(new java.awt.Dimension(400, 300));
        paymentTable.setMinimumSize(new java.awt.Dimension(400, 300));
        paymentTable.setPreferredSize(new java.awt.Dimension(400, 300));
        paymentTable.setRowHeight(25);
        paymentScrollPanel.setViewportView(paymentTable);
        if (paymentTable.getColumnModel().getColumnCount() > 0) {
            paymentTable.getColumnModel().getColumn(0).setPreferredWidth(40);
        }

        backgroundPanel.add(paymentScrollPanel);

        paymentPanel.setLayout(new java.awt.CardLayout());

        formPanel.setOpaque(false);
        formPanel.setLayout(new java.awt.GridLayout(2, 0));

        realEstatePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        realEstatePanel.setMaximumSize(new java.awt.Dimension(300, 200));
        realEstatePanel.setMinimumSize(new java.awt.Dimension(300, 100));
        realEstatePanel.setOpaque(false);
        realEstatePanel.setPreferredSize(new java.awt.Dimension(300, 100));
        realEstatePanel.setLayout(new javax.swing.BoxLayout(realEstatePanel, javax.swing.BoxLayout.PAGE_AXIS));

        addressTextArea.setEditable(false);
        addressTextArea.setColumns(5);
        addressTextArea.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        addressTextArea.setForeground(new java.awt.Color(255, 255, 255));
        addressTextArea.setLineWrap(true);
        addressTextArea.setRows(4);
        addressTextArea.setText("Rua São João Benedito das Areias Cristalinas, 758\n");
        addressTextArea.setWrapStyleWord(true);
        addressTextArea.setAutoscrolls(false);
        addressTextArea.setFocusable(false);
        addressTextArea.setMaximumSize(new java.awt.Dimension(250, 100));
        addressTextArea.setMinimumSize(new java.awt.Dimension(250, 40));
        addressTextArea.setOpaque(false);
        realEstatePanel.add(addressTextArea);

        formPanel.add(realEstatePanel);

        paymentFormPanel.setOpaque(false);
        paymentFormPanel.setLayout(new javax.swing.BoxLayout(paymentFormPanel, javax.swing.BoxLayout.PAGE_AXIS));

        paymentTitlePanel.setMaximumSize(new java.awt.Dimension(10000, 30));
        paymentTitlePanel.setMinimumSize(new java.awt.Dimension(100, 30));
        paymentTitlePanel.setOpaque(false);
        paymentTitlePanel.setPreferredSize(new java.awt.Dimension(100, 30));

        paymentTitleLabel.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        paymentTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        paymentTitleLabel.setText("Novo Pagamento");
        paymentTitlePanel.add(paymentTitleLabel);

        paymentFormPanel.add(paymentTitlePanel);

        paymentDateTextField.setBackground(new java.awt.Color(120, 120, 120));
        paymentDateTextField.setForeground(new java.awt.Color(255, 255, 255));
        try {
            paymentDateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        paymentDateTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        paymentDateTextField.setMaximumSize(new java.awt.Dimension(250, 30));
        paymentDateTextField.setMinimumSize(new java.awt.Dimension(250, 30));
        paymentDateTextField.setName(""); // NOI18N
        paymentDateTextField.setPreferredSize(new java.awt.Dimension(250, 30));
        paymentFormPanel.add(paymentDateTextField);

        paymentMenuPanel.setOpaque(false);

        registerButton.setBackground(new java.awt.Color(40, 40, 80));
        registerButton.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Cadastrar");
        registerButton.setMaximumSize(new java.awt.Dimension(150, 30));
        registerButton.setMinimumSize(new java.awt.Dimension(150, 30));
        registerButton.setPreferredSize(new java.awt.Dimension(150, 30));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        paymentMenuPanel.add(registerButton);

        paymentFormPanel.add(paymentMenuPanel);

        contractButton.setBackground(new java.awt.Color(40, 40, 80));
        contractButton.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        contractButton.setForeground(new java.awt.Color(255, 255, 255));
        contractButton.setText("Contrato");
        contractButton.setMaximumSize(new java.awt.Dimension(150, 30));
        contractButton.setMinimumSize(new java.awt.Dimension(150, 30));
        contractButton.setPreferredSize(new java.awt.Dimension(150, 30));
        contractButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contractButtonActionPerformed(evt);
            }
        });
        contractPanel.add(contractButton);

        paymentFormPanel.add(contractPanel);

        formPanel.add(paymentFormPanel);

        paymentPanel.add(formPanel, "paymentForm");

        ContractImagePanel.setMaximumSize(new java.awt.Dimension(300, 400));
        ContractImagePanel.setMinimumSize(new java.awt.Dimension(300, 400));
        ContractImagePanel.setPreferredSize(new java.awt.Dimension(300, 400));
        ContractImagePanel.setLayout(new javax.swing.BoxLayout(ContractImagePanel, javax.swing.BoxLayout.PAGE_AXIS));

        contractImageScrollPanel.setMaximumSize(new java.awt.Dimension(300, 350));
        contractImageScrollPanel.setMinimumSize(new java.awt.Dimension(300, 350));
        contractImageScrollPanel.setPreferredSize(new java.awt.Dimension(300, 350));
        contractImageScrollPanel.setViewportView(contractImageLabel);

        ContractImagePanel.add(contractImageScrollPanel);

        menu.setMaximumSize(new java.awt.Dimension(300, 50));
        menu.setMinimumSize(new java.awt.Dimension(300, 50));
        menu.setPreferredSize(new java.awt.Dimension(300, 50));

        jButton1.setBackground(new java.awt.Color(40, 40, 80));
        jButton1.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Voltar");
        jButton1.setMaximumSize(new java.awt.Dimension(100, 30));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 30));
        jButton1.setPreferredSize(new java.awt.Dimension(100, 30));
        menu.add(jButton1);

        jButton2.setBackground(new java.awt.Color(40, 40, 80));
        jButton2.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Substituir");
        jButton2.setMaximumSize(new java.awt.Dimension(100, 30));
        jButton2.setMinimumSize(new java.awt.Dimension(100, 30));
        jButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        menu.add(jButton2);

        ContractImagePanel.add(menu);

        paymentPanel.add(ContractImagePanel, "paymentReceipt");

        backgroundPanel.add(paymentPanel);

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 400));

        Image backgroundImage = new ImageIcon(getClass().getResource("/static/icons/background.png")).getImage();
        Image scaledImage = backgroundImage.getScaledInstance(getWidth(), getHeight(), Image.SCALE_SMOOTH);
        backgroundLabel.setIcon(new ImageIcon(scaledImage));
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String date = paymentDateTextField.getText();
        
        if ("  /  /    ".equals(date)) {
            JOptionPane.showMessageDialog(null, "Insira uma data de pagamento válida");
            return;
        }

        String[] paymentDate = date.split("/");

        List<PaymentModel> payments = paymentController.getAllPayments(rental.getId());
        
        int referenceMonth;
        int referenceYear;
        
        if (payments.isEmpty()) {
            referenceMonth = rental.getContractMonth() + 1;
            referenceYear = rental.getContractYear();
            
            if (referenceMonth > 12) {
                referenceMonth = 1;
                referenceYear += 1;
            }
        } else {
            PaymentModel lastPayment = payments.get(0);
            
            referenceMonth = lastPayment.getReference_month() + 1;
            referenceYear = lastPayment.getReference_year();
            
            if (referenceMonth > 12) {
                referenceMonth = 1;
                referenceYear += 1;
            }
        }
        
        PaymentModel payment = new PaymentModel(
                Integer.parseInt(paymentDate[0]),
                Integer.parseInt(paymentDate[1]),
                Integer.parseInt(paymentDate[2]),
                referenceMonth,
                referenceYear,
                rental.getId(),
                ""
            );
            
        paymentController.addPayment(payment);
        JOptionPane.showMessageDialog(null, "Pagamento cadastrado com sucesso");
        
        this.updateTable();
        paymentDateTextField.setText("");
    }//GEN-LAST:event_registerButtonActionPerformed

    private void contractButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contractButtonActionPerformed
        int row = paymentTable.getSelectedRow();
        if (row == -1) return;
        
        String id = String.valueOf(paymentTable.getValueAt(row, 0));
        
        selectedPayment = paymentController.getPaymentById(Integer.parseInt(id));
        
        if (selectedPayment.getContract() == null) {
            // Add document
        } else {
            this.paymentCardLayout.show(paymentPanel, "paymentReceipt");
            
            // Show Contract
        }
    }//GEN-LAST:event_contractButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(int rentalId, String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentRegister(rentalId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContractImagePanel;
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JButton contractButton;
    private javax.swing.JLabel contractImageLabel;
    private javax.swing.JScrollPane contractImageScrollPanel;
    private javax.swing.JPanel contractPanel;
    private javax.swing.JPanel formPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel menu;
    private javax.swing.JFormattedTextField paymentDateTextField;
    private javax.swing.JPanel paymentFormPanel;
    private javax.swing.JPanel paymentMenuPanel;
    private javax.swing.JPanel paymentPanel;
    private javax.swing.JScrollPane paymentScrollPanel;
    private javax.swing.JTable paymentTable;
    private javax.swing.JLabel paymentTitleLabel;
    private javax.swing.JPanel paymentTitlePanel;
    private javax.swing.JPanel realEstatePanel;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables
}
