/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.imobiliaria.views;

import javax.swing.table.DefaultTableModel;

import com.mycompany.imobiliaria.controllers.PaymentController;
import com.mycompany.imobiliaria.controllers.RentalController;
import com.mycompany.imobiliaria.controllers.RealEstateController;
import com.mycompany.imobiliaria.models.PaymentModel;
import com.mycompany.imobiliaria.models.RentalModel;
import com.mycompany.imobiliaria.models.RealEstateModel;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class PaymentRegister extends javax.swing.JFrame {
    private static final PaymentController paymentController = new PaymentController();
    private RentalModel rental;
    
    /**
     * Creates new form PaymentRegister
     */
    public PaymentRegister(int rentalId) {
        initComponents();
        
        RentalController rentalController = new RentalController();   
        this.rental = rentalController.getRentalById(rentalId);
        
        RealEstateController realEstateController = new RealEstateController();   
        RealEstateModel property = realEstateController.getPropertyById(this.rental.getPropertyId());
        
        String address = property.getAddress() + ", " + property.getNumber() + "\n" + 
                property.getNeighborhood() + " - " + property.getCity();;
        addressTextArea.setText(address);
        
        this.updateTable();
    }
    
    private void updateTable() {
        String[] columnNames = {"ID", "Data do Pagamento", "Data de Referência"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0)  {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        for (PaymentModel payment : paymentController.getAllPayments(this.rental.getId())) {
            String paymentDate = String.format(
                "%02d/%02d/%04d", 
                payment.getPayment_day(), 
                payment.getPayment_month(), 
                payment.getPayment_year()
            );
            
            String referenceDate = String.format(
                "%02d/%04d", 
                payment.getReference_month(), 
                payment.getReference_year()
            );

            
            Object[] row = {
                payment.getId(),
                paymentDate,
                referenceDate,
            };
            tableModel.addRow(row);
        }
        
        paymentTable.setModel(tableModel);

        
        int[] preferredWidths = {40, 100, 100};
        for (int i = 0; i < preferredWidths.length; i++) {
            paymentTable.getColumnModel().getColumn(i).setPreferredWidth(preferredWidths[i]);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        paymentTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        addressTextArea = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        paymentDateTextField = new javax.swing.JFormattedTextField();
        jPanel4 = new javax.swing.JPanel();
        registerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pagamentos");
        setMinimumSize(new java.awt.Dimension(700, 400));
        setPreferredSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        paymentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Data do Pagament", "Data de Referência"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        paymentTable.setMinimumSize(new java.awt.Dimension(400, 400));
        paymentTable.setPreferredSize(new java.awt.Dimension(400, 400));
        jScrollPane1.setViewportView(paymentTable);

        getContentPane().add(jScrollPane1);

        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel2.setMaximumSize(new java.awt.Dimension(300, 200));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        addressTextArea.setEditable(false);
        addressTextArea.setColumns(5);
        addressTextArea.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        addressTextArea.setLineWrap(true);
        addressTextArea.setRows(4);
        addressTextArea.setText("Rua São João Benedito das Areias Cristalinas, 758\n");
        addressTextArea.setWrapStyleWord(true);
        addressTextArea.setAutoscrolls(false);
        addressTextArea.setFocusable(false);
        addressTextArea.setMaximumSize(new java.awt.Dimension(250, 100));
        addressTextArea.setMinimumSize(new java.awt.Dimension(250, 40));
        addressTextArea.setOpaque(false);
        jPanel2.add(addressTextArea);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setMaximumSize(new java.awt.Dimension(10000, 30));
        jPanel5.setMinimumSize(new java.awt.Dimension(100, 30));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel1.setText("Novo Pagamento");
        jPanel5.add(jLabel1);

        jPanel3.add(jPanel5);

        try {
            paymentDateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        paymentDateTextField.setMaximumSize(new java.awt.Dimension(250, 30));
        paymentDateTextField.setMinimumSize(new java.awt.Dimension(250, 30));
        paymentDateTextField.setName(""); // NOI18N
        paymentDateTextField.setPreferredSize(new java.awt.Dimension(250, 30));
        jPanel3.add(paymentDateTextField);

        registerButton.setText("Cadastrar");
        registerButton.setMaximumSize(new java.awt.Dimension(150, 30));
        registerButton.setMinimumSize(new java.awt.Dimension(150, 30));
        registerButton.setPreferredSize(new java.awt.Dimension(150, 30));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        jPanel4.add(registerButton);

        jPanel3.add(jPanel4);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        String date = paymentDateTextField.getText();
        
        if ("  /  /    ".equals(date)) {
            JOptionPane.showMessageDialog(null, "Insira uma data de pagamento válida");
            return;
        }

        String[] paymentDate = date.split("/");

        List<PaymentModel> payments = paymentController.getAllPayments(rental.getId());
        
        int referenceMonth;
        int referenceYear;
        
        if (payments.isEmpty()) {
            String[] referenceDate = rental.getContractDate().split("/");
            
            referenceMonth = Integer.parseInt(referenceDate[1]) + 1;
            referenceYear = Integer.parseInt(referenceDate[2]);
            
            if (referenceMonth > 12) {
                referenceMonth = 1;
                referenceYear += 1;
            }
        } else {
            PaymentModel lastPayment = payments.get(0);
            
            referenceMonth = lastPayment.getReference_month() + 1;
            referenceYear = lastPayment.getReference_year();
            
            if (referenceMonth > 12) {
                referenceMonth = 1;
                referenceYear += 1;
            }
        }
        
        PaymentModel payment = new PaymentModel(
                Integer.parseInt(paymentDate[0]),
                Integer.parseInt(paymentDate[1]),
                Integer.parseInt(paymentDate[2]),
                referenceMonth,
                referenceYear,
                rental.getId()
            );
            
        paymentController.addPayment(payment);
        JOptionPane.showMessageDialog(null, "Pagamento cadastrado com sucesso");
        
        this.updateTable();
        paymentDateTextField.setText("");
    }//GEN-LAST:event_registerButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(int rentalId, String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaymentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaymentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaymentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaymentRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaymentRegister(rentalId).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField paymentDateTextField;
    private javax.swing.JTable paymentTable;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables
}
