/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.imobiliaria.views;

import com.mycompany.imobiliaria.controllers.RealEstateController;
import com.mycompany.imobiliaria.controllers.RentalController;
import com.mycompany.imobiliaria.models.RealEstateModel;
import com.mycompany.imobiliaria.models.RentalModel;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author user
 */
public class RealEstate extends javax.swing.JFrame {
    private static final RealEstateController realEstateController = new RealEstateController();
    private static final RentalController rentalController = new RentalController();
    private String rentFormStatus = "Register";
    private int propertyId;
    private int rentalId;
    
    /**
     * Creates new form RealEstate
     * @param propertyId
     */
    public RealEstate(int propertyId) {        
        initComponents();
        
        rentalFormPanel.setVisible(false);

        try {
            RealEstateModel realEstate = realEstateController.getPropertyById(propertyId);
            
            this.propertyId = propertyId;
            addressTextField.setText(realEstate.getAddress());
            numberTextField.setText(realEstate.getNumber());
            neighborhoodTextField.setText(realEstate.getNeighborhood());
            cityTextField.setText(realEstate.getCity());
            areaTextField.setText(String.valueOf(realEstate.getArea()));
            valueTextField.setText(String.valueOf(realEstate.getValue()));
            typeComboBox.setSelectedItem(realEstate.getType());
            roomsComboBox.setSelectedIndex(realEstate.getRooms());
            bathroomsComboBox.setSelectedIndex(realEstate.getBathrooms());
            garageComboBox.setSelectedIndex(realEstate.getGarage());
        } catch (Exception e) {
            System.err.println(e);
            dispose();
        }
        
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        realEstatePanel = new javax.swing.JPanel();
        addressPanel = new javax.swing.JPanel();
        addressFirstColumnPanel = new javax.swing.JPanel();
        addressLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        neighborhoodLabel = new javax.swing.JLabel();
        neighborhoodTextField = new javax.swing.JTextField();
        addressSecondColumnPanel = new javax.swing.JPanel();
        numberLabel = new javax.swing.JLabel();
        numberTextField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        propertyPanel = new javax.swing.JPanel();
        propertyFirstColumnPanel = new javax.swing.JPanel();
        typeLabel = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        roomsLabel = new javax.swing.JLabel();
        roomsComboBox = new javax.swing.JComboBox<>();
        propertySecondColumnPanel = new javax.swing.JPanel();
        bathroomsLabel = new javax.swing.JLabel();
        bathroomsComboBox = new javax.swing.JComboBox<>();
        areaLabel = new javax.swing.JLabel();
        areaTextField = new javax.swing.JTextField();
        propertyThirdColumnPanel = new javax.swing.JPanel();
        valueLabel = new javax.swing.JLabel();
        valueTextField = new javax.swing.JTextField();
        garageLabel = new javax.swing.JLabel();
        garageComboBox = new javax.swing.JComboBox<>();
        bottomMenuPanel = new javax.swing.JPanel();
        returnButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        rentalPanel = new javax.swing.JPanel();
        rentalsPanel = new javax.swing.JPanel();
        contractsTitlePanel = new javax.swing.JPanel();
        contractsTitleLabel = new javax.swing.JLabel();
        rentScrollPanel = new javax.swing.JScrollPane();
        rentTable = new javax.swing.JTable();
        actionPanel = new javax.swing.JPanel();
        openRentFormButton = new javax.swing.JButton();
        rentalFormPanel = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        peoplePanel = new javax.swing.JPanel();
        landLordPanel = new javax.swing.JPanel();
        landLordLabel = new javax.swing.JLabel();
        landLordNameLabel = new javax.swing.JLabel();
        landLordNameTextField = new javax.swing.JTextField();
        landLordCPFLabel = new javax.swing.JLabel();
        landLordCPFTextField = new javax.swing.JFormattedTextField();
        landLordPhoneLabel = new javax.swing.JLabel();
        landLordPhoneTextField = new javax.swing.JFormattedTextField();
        landLordEmailLabel = new javax.swing.JLabel();
        landLordEmailTextField = new javax.swing.JTextField();
        tenantPanel = new javax.swing.JPanel();
        tenantLabel = new javax.swing.JLabel();
        tenantNameLabel = new javax.swing.JLabel();
        tenantNameTextField = new javax.swing.JTextField();
        tenantCPFLabel = new javax.swing.JLabel();
        tenantCPFTextField = new javax.swing.JFormattedTextField();
        tenantPhoneLabel = new javax.swing.JLabel();
        tenantPhoneTextField = new javax.swing.JFormattedTextField();
        tenantEmailLabel = new javax.swing.JLabel();
        tenantEmailTextField = new javax.swing.JTextField();
        contractPane = new javax.swing.JPanel();
        contractFirstColumnPanel = new javax.swing.JPanel();
        contractDateLabel = new javax.swing.JLabel();
        contractDateTextField = new javax.swing.JFormattedTextField();
        paymentDayLabel = new javax.swing.JLabel();
        paymentBaseDateTextField = new javax.swing.JFormattedTextField();
        rentValueLabel = new javax.swing.JLabel();
        rentValueTextField = new javax.swing.JFormattedTextField();
        contractSecondColumnPanel = new javax.swing.JPanel();
        durationLabel = new javax.swing.JLabel();
        durationTextField = new javax.swing.JFormattedTextField();
        statusLabel = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();
        rentOptionsPanel = new javax.swing.JPanel();
        closeRentFormButton = new javax.swing.JButton();
        submitRentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atualizar Imóvel");
        setBackground(new java.awt.Color(38, 116, 255));
        setMinimumSize(new java.awt.Dimension(1000, 550));
        setPreferredSize(new java.awt.Dimension(1000, 550));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        realEstatePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 0, 10));
        realEstatePanel.setMinimumSize(new java.awt.Dimension(600, 600));
        realEstatePanel.setPreferredSize(new java.awt.Dimension(600, 600));
        realEstatePanel.setLayout(new javax.swing.BoxLayout(realEstatePanel, javax.swing.BoxLayout.PAGE_AXIS));

        addressPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        addressPanel.setOpaque(false);
        addressPanel.setLayout(new java.awt.GridLayout(1, 2, 25, 0));

        addressFirstColumnPanel.setOpaque(false);
        addressFirstColumnPanel.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        addressLabel.setText("Endereço:");
        addressFirstColumnPanel.add(addressLabel);
        addressFirstColumnPanel.add(addressTextField);

        neighborhoodLabel.setText("Bairro");
        addressFirstColumnPanel.add(neighborhoodLabel);
        addressFirstColumnPanel.add(neighborhoodTextField);

        addressPanel.add(addressFirstColumnPanel);

        addressSecondColumnPanel.setOpaque(false);
        addressSecondColumnPanel.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        numberLabel.setText("Número:");
        addressSecondColumnPanel.add(numberLabel);
        addressSecondColumnPanel.add(numberTextField);

        cityLabel.setText("Cidade");
        addressSecondColumnPanel.add(cityLabel);
        addressSecondColumnPanel.add(cityTextField);

        addressPanel.add(addressSecondColumnPanel);

        realEstatePanel.add(addressPanel);

        propertyPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 25, 0));
        propertyPanel.setOpaque(false);
        propertyPanel.setLayout(new java.awt.GridLayout(1, 3, 25, 0));

        propertyFirstColumnPanel.setOpaque(false);
        propertyFirstColumnPanel.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        typeLabel.setText("Tipo");
        propertyFirstColumnPanel.add(typeLabel);

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Terreno", "Apartamento", "Chácara" }));
        propertyFirstColumnPanel.add(typeComboBox);

        roomsLabel.setText("Números de quartos");
        propertyFirstColumnPanel.add(roomsLabel);

        roomsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 Quartos", "1 Quarto", "2 Quartos", "3 Quartos", "+4 Quartos" }));
        propertyFirstColumnPanel.add(roomsComboBox);

        propertyPanel.add(propertyFirstColumnPanel);

        propertySecondColumnPanel.setOpaque(false);
        propertySecondColumnPanel.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        bathroomsLabel.setText("Números de banheiros");
        propertySecondColumnPanel.add(bathroomsLabel);

        bathroomsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 Banheiros", "1 Banheiro", "2 Banheiros", "3 Banheiros", "+4 Banheiros" }));
        propertySecondColumnPanel.add(bathroomsComboBox);

        areaLabel.setText("Área do imovel");
        propertySecondColumnPanel.add(areaLabel);
        propertySecondColumnPanel.add(areaTextField);

        propertyPanel.add(propertySecondColumnPanel);

        propertyThirdColumnPanel.setOpaque(false);
        propertyThirdColumnPanel.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        valueLabel.setText("Valor");
        propertyThirdColumnPanel.add(valueLabel);
        propertyThirdColumnPanel.add(valueTextField);

        garageLabel.setText("Garagem");
        propertyThirdColumnPanel.add(garageLabel);

        garageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "1 Carro", "2 Carros", "3 Carros", "+4 Carros" }));
        propertyThirdColumnPanel.add(garageComboBox);

        propertyPanel.add(propertyThirdColumnPanel);

        realEstatePanel.add(propertyPanel);

        bottomMenuPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        bottomMenuPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        bottomMenuPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        returnButton.setText("Voltar");
        returnButton.setPreferredSize(new java.awt.Dimension(100, 30));
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        bottomMenuPanel.add(returnButton);

        deleteButton.setText("Deletar");
        deleteButton.setPreferredSize(new java.awt.Dimension(100, 30));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        bottomMenuPanel.add(deleteButton);

        saveButton.setText("Salvar");
        saveButton.setPreferredSize(new java.awt.Dimension(100, 30));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        bottomMenuPanel.add(saveButton);

        realEstatePanel.add(bottomMenuPanel);

        getContentPane().add(realEstatePanel);

        rentalPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        rentalPanel.setLayout(new javax.swing.BoxLayout(rentalPanel, javax.swing.BoxLayout.PAGE_AXIS));

        rentalsPanel.setLayout(new javax.swing.BoxLayout(rentalsPanel, javax.swing.BoxLayout.PAGE_AXIS));

        contractsTitleLabel.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        contractsTitleLabel.setText("Contratos");
        contractsTitlePanel.add(contractsTitleLabel);

        rentalsPanel.add(contractsTitlePanel);

        rentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        rentScrollPanel.setViewportView(rentTable);

        rentalsPanel.add(rentScrollPanel);

        openRentFormButton.setText("Cadastrar");
        openRentFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openRentFormButtonActionPerformed(evt);
            }
        });
        actionPanel.add(openRentFormButton);

        rentalsPanel.add(actionPanel);

        rentalPanel.add(rentalsPanel);

        rentalFormPanel.setLayout(new javax.swing.BoxLayout(rentalFormPanel, javax.swing.BoxLayout.PAGE_AXIS));

        jLabel27.setFont(new java.awt.Font("Liberation Sans", 0, 18)); // NOI18N
        jLabel27.setText("Novo Contrato");
        jPanel9.add(jLabel27);

        rentalFormPanel.add(jPanel9);

        peoplePanel.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        landLordPanel.setLayout(new java.awt.GridLayout(9, 0));

        landLordLabel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        landLordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landLordLabel.setText("Locador");
        landLordPanel.add(landLordLabel);

        landLordNameLabel.setText("Nome");
        landLordPanel.add(landLordNameLabel);
        landLordPanel.add(landLordNameTextField);

        landLordCPFLabel.setText("CPF");
        landLordPanel.add(landLordCPFLabel);

        try {
            landLordCPFTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        landLordPanel.add(landLordCPFTextField);

        landLordPhoneLabel.setText("Telefone");
        landLordPanel.add(landLordPhoneLabel);

        try {
            landLordPhoneTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        landLordPanel.add(landLordPhoneTextField);

        landLordEmailLabel.setText("Email");
        landLordPanel.add(landLordEmailLabel);
        landLordPanel.add(landLordEmailTextField);

        peoplePanel.add(landLordPanel);

        tenantPanel.setLayout(new java.awt.GridLayout(9, 0));

        tenantLabel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        tenantLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tenantLabel.setText("Locatário");
        tenantPanel.add(tenantLabel);

        tenantNameLabel.setText("Nome");
        tenantPanel.add(tenantNameLabel);
        tenantPanel.add(tenantNameTextField);

        tenantCPFLabel.setText("CPF");
        tenantPanel.add(tenantCPFLabel);

        try {
            tenantCPFTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tenantPanel.add(tenantCPFTextField);

        tenantPhoneLabel.setText("Telefone");
        tenantPanel.add(tenantPhoneLabel);

        try {
            tenantPhoneTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tenantPanel.add(tenantPhoneTextField);

        tenantEmailLabel.setText("Email");
        tenantPanel.add(tenantEmailLabel);
        tenantPanel.add(tenantEmailTextField);

        peoplePanel.add(tenantPanel);

        rentalFormPanel.add(peoplePanel);

        contractPane.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        contractFirstColumnPanel.setLayout(new java.awt.GridLayout(6, 0));

        contractDateLabel.setText("Data do Contrato");
        contractFirstColumnPanel.add(contractDateLabel);

        try {
            contractDateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        contractFirstColumnPanel.add(contractDateTextField);

        paymentDayLabel.setText("Dia do Pagamento");
        contractFirstColumnPanel.add(paymentDayLabel);

        paymentBaseDateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        contractFirstColumnPanel.add(paymentBaseDateTextField);

        rentValueLabel.setText("Valor do aluguel");
        rentValueLabel.setToolTipText("");
        contractFirstColumnPanel.add(rentValueLabel);

        rentValueTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#.00"))));
        contractFirstColumnPanel.add(rentValueTextField);

        contractPane.add(contractFirstColumnPanel);

        contractSecondColumnPanel.setLayout(new java.awt.GridLayout(6, 0));

        durationLabel.setText("Duração");
        contractSecondColumnPanel.add(durationLabel);

        durationTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        contractSecondColumnPanel.add(durationTextField);

        statusLabel.setText("Status");
        contractSecondColumnPanel.add(statusLabel);

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Cancelado", "Vencido" }));
        contractSecondColumnPanel.add(statusComboBox);

        contractPane.add(contractSecondColumnPanel);

        rentalFormPanel.add(contractPane);

        closeRentFormButton.setText("Voltar");
        closeRentFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeRentFormButtonActionPerformed(evt);
            }
        });
        rentOptionsPanel.add(closeRentFormButton);

        submitRentButton.setText("Enviar");
        submitRentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitRentButtonActionPerformed(evt);
            }
        });
        rentOptionsPanel.add(submitRentButton);

        rentalFormPanel.add(rentOptionsPanel);

        rentalPanel.add(rentalFormPanel);

        getContentPane().add(rentalPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            realEstateController.deleteProperty(this.propertyId);
            JOptionPane.showMessageDialog(null, "Imóvel deletado com sucesso");
            dispose();
        } catch (Exception e) {
            System.err.println(e);
            dispose();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            areaTextField.setBackground(Color.WHITE);
            valueTextField.setBackground(Color.WHITE);
            
            if (addressTextField.getText().length() == 0) {
                addressTextField.setBackground(Color.RED);
                addressTextField.setToolTipText("Campo obrigatório");
                System.err.println("Required field");
                return;
            }
            
            if (neighborhoodTextField.getText().length() == 0) {
                neighborhoodTextField.setBackground(Color.RED);
                neighborhoodTextField.setToolTipText("Campo obrigatório");
                System.err.println("Required field");
                return;
            }
            
            if (cityTextField.getText().length() == 0) {
                cityTextField.setBackground(Color.RED);
                cityTextField.setToolTipText("Campo obrigatório");
                System.err.println("Required field");
                return;
            }
            
            if (!isValidDouble(areaTextField.getText().replace(",", "."))) {
                areaTextField.setBackground(Color.RED);
                areaTextField.setToolTipText("Valor invalido, formato: 0,00");
                System.err.println("Invalid area value");
                return;
            }
            
            if (!isValidDouble(valueTextField.getText().replace(",", "."))) {
                valueTextField.setBackground(Color.RED);
                valueTextField.setToolTipText("Valor invalido, formato: 0,00");
                System.err.println("Invalid value");
                return;
            }
            
            RealEstateModel realEstate = new RealEstateModel(
                this.propertyId,
                addressTextField.getText(),
                neighborhoodTextField.getText(),
                numberTextField.getText(),
                cityTextField.getText(),
                typeComboBox.getSelectedItem().toString(),
                roomsComboBox.getSelectedIndex(),
                bathroomsComboBox.getSelectedIndex(),
                Double.valueOf(areaTextField.getText().replace(",", ".")),
                Double.valueOf(valueTextField.getText().replace(",", ".")),
                garageComboBox.getSelectedIndex()
            );
            
            realEstateController.updateProperty(realEstate);
            
            JOptionPane.showMessageDialog(null, "Imóvel atualizado com sucesso");
        } catch(Exception e) {
            System.err.println("Error: " + e);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void openRentFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openRentFormButtonActionPerformed
        rentalsPanel.setVisible(false);
        rentalFormPanel.setVisible(true);
        this.rentFormStatus = "Register";
        
         contractDateTextField.setText("");
        paymentBaseDateTextField.setText("");
        rentValueTextField.setText("");
        landLordNameTextField.setText("");
        landLordCPFTextField.setText("");
        landLordPhoneTextField.setText("");
        landLordEmailTextField.setText("");
        tenantNameTextField.setText("");
        tenantCPFTextField.setText("");
        tenantPhoneTextField.setText("");
        tenantEmailTextField.setText("");
        durationTextField.setText("");
        statusComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_openRentFormButtonActionPerformed

    private void closeRentFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeRentFormButtonActionPerformed
        rentalsPanel.setVisible(true);
        rentalFormPanel.setVisible(false);
    }//GEN-LAST:event_closeRentFormButtonActionPerformed

    private void submitRentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitRentButtonActionPerformed
        try {
            paymentBaseDateTextField.setBackground(Color.WHITE);
            durationTextField.setBackground(Color.WHITE);
            rentValueTextField.setBackground(Color.WHITE);
            
            if (!isValidInteger(paymentBaseDateTextField.getText()) ||
                Integer.parseInt(paymentBaseDateTextField.getText()) < 1 ||
                Integer.parseInt(paymentBaseDateTextField.getText()) > 28) {
                paymentBaseDateTextField.setBackground(Color.RED);
                paymentBaseDateTextField.setToolTipText("Campo númerico entre 1 e 28");
                System.err.println("Payment day field must be an integer");
                return;
            }
            
            if (!isValidInteger(durationTextField.getText())) {
                durationTextField.setBackground(Color.RED);
                durationTextField.setToolTipText("Campo númerico");
                System.err.println("Duration field must be an integer");
                return;
            }
            
            if (!isValidDouble(rentValueTextField.getText())) {
                rentValueTextField.setBackground(Color.RED);
                rentValueTextField.setToolTipText("Campo númerico, use o formato 0,00");
                System.err.println("Duration field must be a double");
                return;
            }
            
            int paymentDay = Integer.parseInt(paymentBaseDateTextField.getText());
            int duration = Integer.parseInt(durationTextField.getText());
            double rentValue = Double.parseDouble(rentValueTextField.getText());
            RentalModel rental = new RentalModel(
                contractDateTextField.getText(),
                paymentDay,
                rentValue,
                landLordNameTextField.getText(),
                landLordCPFTextField.getText(),
                landLordPhoneTextField.getText(),
                landLordEmailTextField.getText(),
                tenantNameTextField.getText(),
                tenantCPFTextField.getText(),
                tenantPhoneTextField.getText(),
                tenantEmailTextField.getText(),
                duration,
                addMonthsToDate(contractDateTextField.getText(), duration),
                this.propertyId,
                statusComboBox.getSelectedItem().toString()
            );
            
            if (this.rentFormStatus.equals("Register")) {
                rentalController.addRental(rental);
            } else {
                rental.setId(this.rentalId);
                rentalController.updateRental(rental);
            }
            
            updateTable();
            rentalsPanel.setVisible(true);
            rentalFormPanel.setVisible(false);
            
            JOptionPane.showMessageDialog(null, "Aluguel cadastrado com sucesso");
        } catch(Exception e) {
            System.err.println("Error: " + e);
        }
    }//GEN-LAST:event_submitRentButtonActionPerformed

    public void openUpdateForm(int rentalId) {
        this.rentalId = rentalId;
        rentalsPanel.setVisible(false);
        rentalFormPanel.setVisible(true);
        this.rentFormStatus = "Update";
        

        RentalModel rental = rentalController.getRentalById(rentalId);
        
        String rentValue = String.valueOf(rental.getRentValue());
        
        contractDateTextField.setText(rental.getContractDate());
        paymentBaseDateTextField.setText(String.valueOf(rental.getPaymentBaseDate()));
        rentValueTextField.setText(rentValue);
        landLordNameTextField.setText(rental.getLandlordName());
        landLordCPFTextField.setText(rental.getLandlordCpf());
        landLordPhoneTextField.setText(rental.getLandlordPhone());
        landLordEmailTextField.setText(rental.getLandlordEmail());
        tenantNameTextField.setText(rental.getTenantName());
        tenantCPFTextField.setText(rental.getTenantCpf());
        tenantPhoneTextField.setText(rental.getTenantPhone());
        tenantEmailTextField.setText(rental.getTenantEmail());
        durationTextField.setText(String.valueOf(rental.getDurationMonths()));
        statusComboBox.setSelectedItem(rental.getStatus());
    }
    
    public void updateTable() {
        String[] columnNames = {"ID", "Data", "Vencimento", "Status", "Editar", "Aluguel"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0)  {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 4 || column == 5;
            }
        };
        
        for (RentalModel rental : rentalController.getAllRentalsByPropertyId(this.propertyId)) {
            Object[] row = {
                rental.getId(),
                rental.getContractDate(),
                rental.getDueDate(),
                rental.getStatus(),
                "",
                "",
            };
            tableModel.addRow(row);
        }
        
        rentTable.setModel(tableModel);
        
        rentTable.getColumn("Editar").setCellRenderer(new RentalButtonRenderer());
        rentTable.getColumn("Editar").setCellEditor(new RentalButtonEditor(new JCheckBox(), rentTable, this));
        
        rentTable.getColumn("Aluguel").setCellRenderer(new PaymentButtonRenderer());
        rentTable.getColumn("Aluguel").setCellEditor(new PaymentButtonEditor(new JCheckBox(), rentTable));
        
        int[] preferredWidths = {40, 100, 100, 80, 40, 40};
        for (int i = 0; i < preferredWidths.length; i++) {
            rentTable.getColumnModel().getColumn(i).setPreferredWidth(preferredWidths[i]);
        }
    }
    
    private boolean isValidInteger(String input) {
        try {
            Integer.parseInt(input);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    private boolean isValidDouble(String input) {
        try {
            Double.parseDouble(input);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }


    public static String addMonthsToDate(String dateStr, int monthsToAdd) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate date = LocalDate.parse(dateStr, formatter);
        LocalDate updatedDate = date.plusMonths(monthsToAdd);
        return updatedDate.format(formatter);
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(int id, String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealEstate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealEstate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealEstate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealEstate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealEstate(id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JPanel addressFirstColumnPanel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JPanel addressPanel;
    private javax.swing.JPanel addressSecondColumnPanel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel areaLabel;
    private javax.swing.JTextField areaTextField;
    private javax.swing.JComboBox<String> bathroomsComboBox;
    private javax.swing.JLabel bathroomsLabel;
    private javax.swing.JPanel bottomMenuPanel;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JButton closeRentFormButton;
    private javax.swing.JLabel contractDateLabel;
    private javax.swing.JFormattedTextField contractDateTextField;
    private javax.swing.JPanel contractFirstColumnPanel;
    private javax.swing.JPanel contractPane;
    private javax.swing.JPanel contractSecondColumnPanel;
    private javax.swing.JLabel contractsTitleLabel;
    private javax.swing.JPanel contractsTitlePanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JFormattedTextField durationTextField;
    private javax.swing.JComboBox<String> garageComboBox;
    private javax.swing.JLabel garageLabel;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JLabel landLordCPFLabel;
    private javax.swing.JFormattedTextField landLordCPFTextField;
    private javax.swing.JLabel landLordEmailLabel;
    private javax.swing.JTextField landLordEmailTextField;
    private javax.swing.JLabel landLordLabel;
    private javax.swing.JLabel landLordNameLabel;
    private javax.swing.JTextField landLordNameTextField;
    private javax.swing.JPanel landLordPanel;
    private javax.swing.JLabel landLordPhoneLabel;
    private javax.swing.JFormattedTextField landLordPhoneTextField;
    private javax.swing.JLabel neighborhoodLabel;
    private javax.swing.JTextField neighborhoodTextField;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JButton openRentFormButton;
    private javax.swing.JFormattedTextField paymentBaseDateTextField;
    private javax.swing.JLabel paymentDayLabel;
    private javax.swing.JPanel peoplePanel;
    private javax.swing.JPanel propertyFirstColumnPanel;
    private javax.swing.JPanel propertyPanel;
    private javax.swing.JPanel propertySecondColumnPanel;
    private javax.swing.JPanel propertyThirdColumnPanel;
    private javax.swing.JPanel realEstatePanel;
    private javax.swing.JPanel rentOptionsPanel;
    private javax.swing.JScrollPane rentScrollPanel;
    private javax.swing.JTable rentTable;
    private javax.swing.JLabel rentValueLabel;
    private javax.swing.JFormattedTextField rentValueTextField;
    private javax.swing.JPanel rentalFormPanel;
    private javax.swing.JPanel rentalPanel;
    private javax.swing.JPanel rentalsPanel;
    private javax.swing.JButton returnButton;
    private javax.swing.JComboBox<String> roomsComboBox;
    private javax.swing.JLabel roomsLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton submitRentButton;
    private javax.swing.JLabel tenantCPFLabel;
    private javax.swing.JFormattedTextField tenantCPFTextField;
    private javax.swing.JLabel tenantEmailLabel;
    private javax.swing.JTextField tenantEmailTextField;
    private javax.swing.JLabel tenantLabel;
    private javax.swing.JLabel tenantNameLabel;
    private javax.swing.JTextField tenantNameTextField;
    private javax.swing.JPanel tenantPanel;
    private javax.swing.JLabel tenantPhoneLabel;
    private javax.swing.JFormattedTextField tenantPhoneTextField;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTextField valueTextField;
    // End of variables declaration//GEN-END:variables
}

class RentalButtonRenderer extends JButton implements TableCellRenderer {
    public RentalButtonRenderer() {
        setToolTipText("Editar");

        ImageIcon pencilIcon = new ImageIcon(getClass().getResource("/static/icons/edit.png"));
        setIcon(pencilIcon);

        setText("");

        setHorizontalAlignment(SwingConstants.CENTER);
        setBorderPainted(false);
        setContentAreaFilled(false);
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
        boolean isSelected, boolean hasFocus, int row, int column) {
        return this;
    }
}

class PaymentButtonRenderer extends JButton implements TableCellRenderer {
    public PaymentButtonRenderer() {
        setToolTipText("Editar");

        ImageIcon pencilIcon = new ImageIcon(getClass().getResource("/static/icons/wallet.png"));
        setIcon(pencilIcon);

        setText("");

        setHorizontalAlignment(SwingConstants.CENTER);
        setBorderPainted(false);
        setContentAreaFilled(false);
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
        boolean isSelected, boolean hasFocus, int row, int column) {
        return this;
    }
}

class RentalButtonEditor extends DefaultCellEditor {
    private JButton button;
    private boolean isPushed;
    private JTable table;
    private JFrame mainFrame;

    public RentalButtonEditor(JCheckBox checkBox, JTable table, JFrame mainFrame) {
        super(checkBox);
        this.table = table;
        this.mainFrame = mainFrame;
        button = new JButton("");
        button.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                fireEditingStopped();
                int selectedRow = table.getSelectedRow();
                Object idValue = table.getValueAt(selectedRow, 0);
                openDetailsWindow(idValue);
            }
        });
    }

    @Override
    public Component getTableCellEditorComponent(JTable table, Object value,
        boolean isSelected, int row, int column) {
        isPushed = true;
        return button;
    }

    @Override
    public boolean stopCellEditing() {
        isPushed = false;
        return super.stopCellEditing();
    }

    private void openDetailsWindow(Object idObj) {
        int id = Integer.parseInt(idObj.toString());
        
        if (mainFrame instanceof RealEstate) {
            ((RealEstate) mainFrame).openUpdateForm(id);
        }
    }
}

class PaymentButtonEditor extends DefaultCellEditor {
    private JButton button;
    private boolean isPushed;
    private JTable table;
    private PaymentRegister paymentRegisterFrame = null;

    public PaymentButtonEditor(JCheckBox checkBox, JTable table) {
        super(checkBox);
        this.table = table;
        button = new JButton("");
        button.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                fireEditingStopped();
                int selectedRow = table.getSelectedRow();
                Object idValue = table.getValueAt(selectedRow, 0);
                openDetailsWindow(idValue);
            }
        });
    }

    @Override
    public Component getTableCellEditorComponent(JTable table, Object value,
        boolean isSelected, int row, int column) {
        isPushed = true;
        return button;
    }

    @Override
    public boolean stopCellEditing() {
        isPushed = false;
        return super.stopCellEditing();
    }

    private void openDetailsWindow(Object idObj) {
        int id = Integer.parseInt(idObj.toString());
        
         if (paymentRegisterFrame == null || !paymentRegisterFrame.isDisplayable()) {
            paymentRegisterFrame = new PaymentRegister(id);
            paymentRegisterFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            paymentRegisterFrame.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    paymentRegisterFrame = null;
                }
            });
            
            paymentRegisterFrame.setVisible(true);
        } else {
            paymentRegisterFrame.toFront();
            paymentRegisterFrame.requestFocus();
            paymentRegisterFrame.setState(JFrame.NORMAL);
        }
    }
}
