/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.imobiliaria.views;

import java.awt.Color;
import javax.swing.JOptionPane;

import com.mycompany.imobiliaria.models.RealEstateModel;
import com.mycompany.imobiliaria.controllers.RealEstateController;

/**
 *
 * @author user
 */
public class RealEstateFormRegister extends javax.swing.JFrame {
    private static final RealEstateController realEstateController = new RealEstateController();
    
    /**
     * Creates new form PropertyForm
     */
    public RealEstateFormRegister() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addressPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        neighborhoodTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        numberTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        propertyPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        roomsComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bathroomsComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        areaTextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        valueTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        garageComboBox = new javax.swing.JComboBox<>();
        bottomMenuPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        cleanButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Imóvel");
        setMinimumSize(new java.awt.Dimension(700, 440));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        addressPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 25, 0, 25));
        addressPanel.setOpaque(false);
        addressPanel.setLayout(new java.awt.GridLayout(1, 2, 25, 0));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jLabel1.setText("Endereço:");
        jPanel3.add(jLabel1);
        jPanel3.add(addressTextField);

        jLabel2.setText("Bairro");
        jPanel3.add(jLabel2);
        jPanel3.add(neighborhoodTextField);

        addressPanel.add(jPanel3);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jLabel3.setText("Número:");
        jPanel4.add(jLabel3);
        jPanel4.add(numberTextField);

        jLabel4.setText("Cidade");
        jPanel4.add(jLabel4);
        jPanel4.add(cityTextField);

        addressPanel.add(jPanel4);

        getContentPane().add(addressPanel);

        propertyPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 25, 25, 25));
        propertyPanel.setOpaque(false);
        propertyPanel.setLayout(new java.awt.GridLayout(1, 3, 25, 0));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jLabel5.setText("Tipo");
        jPanel1.add(jLabel5);

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Terreno", "Apartamento", "Chácara" }));
        jPanel1.add(typeComboBox);

        jLabel6.setText("Números de quartos");
        jPanel1.add(jLabel6);

        roomsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 Quartos", "1 Quarto", "2 Quartos", "3 Quartos", "+4 Quartos" }));
        jPanel1.add(roomsComboBox);

        propertyPanel.add(jPanel1);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jLabel7.setText("Números de banheiros");
        jPanel2.add(jLabel7);

        bathroomsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 Banheiros", "1 Banheiro", "2 Banheiros", "3 Banheiros", "+4 Banheiros" }));
        jPanel2.add(bathroomsComboBox);

        jLabel8.setText("Área do imovel");
        jPanel2.add(jLabel8);
        jPanel2.add(areaTextField);

        propertyPanel.add(jPanel2);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jLabel9.setText("Valor");
        jPanel5.add(jLabel9);
        jPanel5.add(valueTextField);

        jLabel10.setText("Garagem");
        jPanel5.add(jLabel10);

        garageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "1 Carro", "2 Carros", "3 Carros", "+4 Carros" }));
        jPanel5.add(garageComboBox);

        propertyPanel.add(jPanel5);

        getContentPane().add(propertyPanel);

        bottomMenuPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        bottomMenuPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        bottomMenuPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        cancelButton.setText("Cancelar");
        cancelButton.setPreferredSize(new java.awt.Dimension(100, 30));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        bottomMenuPanel.add(cancelButton);

        cleanButton.setText("Limpar");
        cleanButton.setPreferredSize(new java.awt.Dimension(100, 30));
        cleanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanButtonActionPerformed(evt);
            }
        });
        bottomMenuPanel.add(cleanButton);

        saveButton.setText("Salvar");
        saveButton.setPreferredSize(new java.awt.Dimension(100, 30));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        bottomMenuPanel.add(saveButton);

        getContentPane().add(bottomMenuPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            addressTextField.setBackground(Color.WHITE);
            neighborhoodTextField.setBackground(Color.WHITE);
            cityTextField.setBackground(Color.WHITE);
            areaTextField.setBackground(Color.WHITE);
            valueTextField.setBackground(Color.WHITE);
            
            if (addressTextField.getText().length() == 0) {
                addressTextField.setBackground(Color.RED);
                addressTextField.setToolTipText("Campo obrigatório");
                System.out.println("Required field");
                return;
            }
            
            if (neighborhoodTextField.getText().length() == 0) {
                neighborhoodTextField.setBackground(Color.RED);
                neighborhoodTextField.setToolTipText("Campo obrigatório");
                System.out.println("Required field");
                return;
            }
            
            if (cityTextField.getText().length() == 0) {
                cityTextField.setBackground(Color.RED);
                cityTextField.setToolTipText("Campo obrigatório");
                System.out.println("Required field");
                return;
            }
            
            if (!isValidDouble(areaTextField.getText().replace(",", "."))) {
                areaTextField.setBackground(Color.RED);
                areaTextField.setToolTipText("Valor invalido, formato: 0,00");
                System.out.println("Invalid area value");
                return;
            }
            
            if (!isValidDouble(valueTextField.getText().replace(",", "."))) {
                valueTextField.setBackground(Color.RED);
                valueTextField.setToolTipText("Valor invalido, formato: 0,00");
                System.out.println("Invalid value");
                return;
            }
            
            RealEstateModel realEstate = new RealEstateModel(
                addressTextField.getText(),
                neighborhoodTextField.getText(),
                numberTextField.getText(),
                cityTextField.getText(),
                typeComboBox.getSelectedItem().toString(),
                roomsComboBox.getSelectedIndex(),
                bathroomsComboBox.getSelectedIndex(),
                Double.valueOf(areaTextField.getText().replace(",", ".")),
                Double.valueOf(valueTextField.getText().replace(",", ".")),
                garageComboBox.getSelectedIndex()
            );
            
            realEstateController.addProperty(realEstate);
            
            JOptionPane.showMessageDialog(null, "Imóvel cadastrado com sucesso");
            dispose();
        } catch(Exception e) {
            System.out.println("Error: " + e);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void cleanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanButtonActionPerformed
        addressTextField.setText("");
        numberTextField.setText("");
        neighborhoodTextField.setText("");
        cityTextField.setText("");
        areaTextField.setText("");
        valueTextField.setText("");
        typeComboBox.setSelectedIndex(0);
        roomsComboBox.setSelectedIndex(0);
        bathroomsComboBox.setSelectedIndex(0);
        garageComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_cleanButtonActionPerformed

    private boolean isValidDouble(String input) {
        try {
            Double.parseDouble(input);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealEstateFormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealEstateFormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealEstateFormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealEstateFormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealEstateFormRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addressPanel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField areaTextField;
    private javax.swing.JComboBox<String> bathroomsComboBox;
    private javax.swing.JPanel bottomMenuPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JButton cleanButton;
    private javax.swing.JComboBox<String> garageComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTextField neighborhoodTextField;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JPanel propertyPanel;
    private javax.swing.JComboBox<String> roomsComboBox;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JTextField valueTextField;
    // End of variables declaration//GEN-END:variables
}
