/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.imobiliaria.views;

import com.mycompany.imobiliaria.controllers.RealEstateController;
import com.mycompany.imobiliaria.controllers.RentalController;
import com.mycompany.imobiliaria.models.RealEstateModel;
import com.mycompany.imobiliaria.models.RentalModel;
import java.awt.CardLayout;

import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.file.Files;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.rendering.PDFRenderer;

/**
 *
 * @author user
 */
public class RealEstate extends javax.swing.JFrame {
    private static final RealEstateController realEstateController = new RealEstateController();
    private static final RentalController rentalController = new RentalController();
    private String rentFormStatus = "Register";
    private int propertyId;
    private int rentalId;
    private CardLayout rentalCardLayout;
    private RentalModel selectedRent;
    
    /**
     * Creates new form RealEstate
     * @param propertyId
     */
    public RealEstate(int propertyId) {        
        initComponents();
        
        this.rentalCardLayout = ((CardLayout) rentalPanel.getLayout());
        
        setLayout(null);
        backgroundLabel.setBounds(0, 0, getWidth(), getHeight());
        
        Image backgroundImage = new ImageIcon(getClass().getResource("/static/icons/background.png")).getImage();
        Image scaledImage = backgroundImage.getScaledInstance(getWidth(), getHeight(), Image.SCALE_SMOOTH);
        backgroundLabel.setIcon(new ImageIcon(scaledImage));

        try {
            RealEstateModel realEstate = realEstateController.getPropertyById(propertyId);
            
            this.propertyId = propertyId;
            addressTextField.setText(realEstate.getAddress());
            numberTextField.setText(realEstate.getNumber());
            neighborhoodTextField.setText(realEstate.getNeighborhood());
            cityTextField.setText(realEstate.getCity());
            areaTextField.setText(String.valueOf(realEstate.getArea()));
            valueTextField.setText(String.valueOf(realEstate.getValue()));
            typeComboBox.setSelectedItem(realEstate.getType());
            roomsComboBox.setSelectedIndex(realEstate.getRooms());
            bathroomsComboBox.setSelectedIndex(realEstate.getBathrooms());
            garageComboBox.setSelectedIndex(realEstate.getGarage());
        } catch (Exception e) {
            System.err.println(e);
            dispose();
        }
        
        rentTable.getColumn("Editar").setCellRenderer(new RentalButtonRenderer());
        rentTable.getColumn("Editar").setCellEditor(new RentalButtonEditor(new JCheckBox(), rentTable, this));
        
        rentTable.getColumn("Aluguel").setCellRenderer(new PaymentButtonRenderer());
        rentTable.getColumn("Aluguel").setCellEditor(new PaymentButtonEditor(new JCheckBox(), rentTable));
        
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        realEstatePanel = new javax.swing.JPanel();
        addressPanel = new javax.swing.JPanel();
        addressFirstColumnPanel = new javax.swing.JPanel();
        addressLabel = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        neighborhoodLabel = new javax.swing.JLabel();
        neighborhoodTextField = new javax.swing.JTextField();
        addressSecondColumnPanel = new javax.swing.JPanel();
        numberLabel = new javax.swing.JLabel();
        numberTextField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        propertyPanel = new javax.swing.JPanel();
        propertyFirstColumnPanel = new javax.swing.JPanel();
        typeLabel = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        roomsLabel = new javax.swing.JLabel();
        roomsComboBox = new javax.swing.JComboBox<>();
        propertySecondColumnPanel = new javax.swing.JPanel();
        bathroomsLabel = new javax.swing.JLabel();
        bathroomsComboBox = new javax.swing.JComboBox<>();
        areaLabel = new javax.swing.JLabel();
        areaTextField = new com.mycompany.imobiliaria.views.components.JNumberTextField();
        propertyThirdColumnPanel = new javax.swing.JPanel();
        valueLabel = new javax.swing.JLabel();
        valueTextField = new com.mycompany.imobiliaria.views.components.JNumberTextField();
        garageLabel = new javax.swing.JLabel();
        garageComboBox = new javax.swing.JComboBox<>();
        bottomMenuPanel = new javax.swing.JPanel();
        returnButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        rentalPanel = new javax.swing.JPanel();
        rentPanel = new javax.swing.JPanel();
        contractsTitlePanel = new javax.swing.JPanel();
        contractsTitleLabel = new javax.swing.JLabel();
        rentScrollPanel = new javax.swing.JScrollPane();
        rentTable = new javax.swing.JTable();
        actionPanel = new javax.swing.JPanel();
        openRentFormButton = new javax.swing.JButton();
        documentButton = new javax.swing.JButton();
        rentFormPanel = new javax.swing.JPanel();
        titleRentRegisterPanel = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        peoplePanel = new javax.swing.JPanel();
        landLordPanel = new javax.swing.JPanel();
        landLordLabel = new javax.swing.JLabel();
        landLordNameLabel = new javax.swing.JLabel();
        landLordNameTextField = new javax.swing.JTextField();
        landLordCPFLabel = new javax.swing.JLabel();
        landLordCPFTextField = new javax.swing.JFormattedTextField();
        landLordPhoneLabel = new javax.swing.JLabel();
        landLordPhoneTextField = new javax.swing.JFormattedTextField();
        landLordEmailLabel = new javax.swing.JLabel();
        landLordEmailTextField = new javax.swing.JTextField();
        tenantPanel = new javax.swing.JPanel();
        tenantLabel = new javax.swing.JLabel();
        tenantNameLabel = new javax.swing.JLabel();
        tenantNameTextField = new javax.swing.JTextField();
        tenantCPFLabel = new javax.swing.JLabel();
        tenantCPFTextField = new javax.swing.JFormattedTextField();
        tenantPhoneLabel = new javax.swing.JLabel();
        tenantPhoneTextField = new javax.swing.JFormattedTextField();
        tenantEmailLabel = new javax.swing.JLabel();
        tenantEmailTextField = new javax.swing.JTextField();
        contractPane = new javax.swing.JPanel();
        contractFirstColumnPanel = new javax.swing.JPanel();
        contractDateLabel = new javax.swing.JLabel();
        contractDateTextField = new javax.swing.JFormattedTextField();
        paymentDayLabel = new javax.swing.JLabel();
        paymentBaseDateTextField = new javax.swing.JFormattedTextField();
        rentValueLabel = new javax.swing.JLabel();
        rentValueTextField = new com.mycompany.imobiliaria.views.components.JNumberTextField();
        contractSecondColumnPanel = new javax.swing.JPanel();
        durationLabel = new javax.swing.JLabel();
        durationTextField = new javax.swing.JFormattedTextField();
        statusLabel = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();
        rentOptionsPanel = new javax.swing.JPanel();
        closeRentFormButton = new javax.swing.JButton();
        submitRentButton = new javax.swing.JButton();
        contractPanel = new javax.swing.JPanel();
        contractImagePanel = new javax.swing.JPanel();
        imageScrollPanel = new java.awt.ScrollPane();
        contractImageLabel = new javax.swing.JLabel();
        contractMenuPanel = new javax.swing.JPanel();
        returnRentsButton = new javax.swing.JButton();
        changeDocumentButton = new javax.swing.JButton();
        downloadButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atualizar Imóvel");
        setBackground(new java.awt.Color(38, 116, 255));
        setMaximumSize(new java.awt.Dimension(1000, 650));
        setMinimumSize(new java.awt.Dimension(1000, 650));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setMinimumSize(new java.awt.Dimension(844, 650));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(100, 650));
        backgroundPanel.setBackground(new java.awt.Color(40, 40, 40, 160));
        backgroundPanel.setBorder(null);
        backgroundPanel.setLayout(new javax.swing.BoxLayout(backgroundPanel, javax.swing.BoxLayout.LINE_AXIS));

        realEstatePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 30, 0, 30));
        realEstatePanel.setMaximumSize(new java.awt.Dimension(600, 440));
        realEstatePanel.setMinimumSize(new java.awt.Dimension(600, 440));
        realEstatePanel.setOpaque(false);
        realEstatePanel.setPreferredSize(new java.awt.Dimension(600, 440));
        realEstatePanel.setLayout(new javax.swing.BoxLayout(realEstatePanel, javax.swing.BoxLayout.PAGE_AXIS));

        addressPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        addressPanel.setOpaque(false);
        addressPanel.setLayout(new java.awt.GridLayout(1, 2, 25, 0));

        addressFirstColumnPanel.setOpaque(false);
        addressFirstColumnPanel.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        addressLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(255, 255, 255));
        addressLabel.setText("Endereço:");
        addressFirstColumnPanel.add(addressLabel);

        addressTextField.setBackground(new java.awt.Color(120, 120, 120));
        addressTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        addressTextField.setForeground(new java.awt.Color(255, 255, 255));
        addressFirstColumnPanel.add(addressTextField);

        neighborhoodLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        neighborhoodLabel.setForeground(new java.awt.Color(255, 255, 255));
        neighborhoodLabel.setText("Bairro");
        addressFirstColumnPanel.add(neighborhoodLabel);

        neighborhoodTextField.setBackground(new java.awt.Color(120, 120, 120));
        neighborhoodTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        neighborhoodTextField.setForeground(new java.awt.Color(255, 255, 255));
        addressFirstColumnPanel.add(neighborhoodTextField);

        addressPanel.add(addressFirstColumnPanel);

        addressSecondColumnPanel.setOpaque(false);
        addressSecondColumnPanel.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        numberLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        numberLabel.setForeground(new java.awt.Color(255, 255, 255));
        numberLabel.setText("Número:");
        addressSecondColumnPanel.add(numberLabel);

        numberTextField.setBackground(new java.awt.Color(120, 120, 120));
        numberTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        numberTextField.setForeground(new java.awt.Color(255, 255, 255));
        addressSecondColumnPanel.add(numberTextField);

        cityLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        cityLabel.setForeground(new java.awt.Color(255, 255, 255));
        cityLabel.setText("Cidade");
        addressSecondColumnPanel.add(cityLabel);

        cityTextField.setBackground(new java.awt.Color(120, 120, 120));
        cityTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        cityTextField.setForeground(new java.awt.Color(255, 255, 255));
        addressSecondColumnPanel.add(cityTextField);

        addressPanel.add(addressSecondColumnPanel);

        realEstatePanel.add(addressPanel);

        propertyPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 25, 0));
        propertyPanel.setOpaque(false);
        propertyPanel.setLayout(new java.awt.GridLayout(1, 3, 25, 0));

        propertyFirstColumnPanel.setOpaque(false);
        propertyFirstColumnPanel.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        typeLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        typeLabel.setForeground(new java.awt.Color(255, 255, 255));
        typeLabel.setText("Tipo");
        propertyFirstColumnPanel.add(typeLabel);

        typeComboBox.setBackground(new java.awt.Color(120, 120, 120));
        typeComboBox.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        typeComboBox.setForeground(new java.awt.Color(255, 255, 255));
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Terreno", "Apartamento", "Chácara" }));
        typeComboBox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        typeComboBox.getEditor().getEditorComponent().setBackground(new java.awt.Color(120, 120, 120));
        typeComboBox.getEditor().getEditorComponent().setForeground(new java.awt.Color(255, 255, 255));
        ((javax.swing.JComponent) typeComboBox.getEditor().getEditorComponent()).setBorder(new javax.swing.border.EmptyBorder(0, 0, 0, 0));
        propertyFirstColumnPanel.add(typeComboBox);

        roomsLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        roomsLabel.setForeground(new java.awt.Color(255, 255, 255));
        roomsLabel.setText("Números de quartos");
        propertyFirstColumnPanel.add(roomsLabel);

        roomsComboBox.setBackground(new java.awt.Color(120, 120, 120));
        roomsComboBox.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        roomsComboBox.setForeground(new java.awt.Color(255, 255, 255));
        roomsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 Quartos", "1 Quarto", "2 Quartos", "3 Quartos", "+4 Quartos" }));
        roomsComboBox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        roomsComboBox.getEditor().getEditorComponent().setBackground(new java.awt.Color(120, 120, 120));
        roomsComboBox.getEditor().getEditorComponent().setForeground(new java.awt.Color(255, 255, 255));
        ((javax.swing.JComponent) roomsComboBox.getEditor().getEditorComponent()).setBorder(new javax.swing.border.EmptyBorder(0, 0, 0, 0));
        propertyFirstColumnPanel.add(roomsComboBox);

        propertyPanel.add(propertyFirstColumnPanel);

        propertySecondColumnPanel.setOpaque(false);
        propertySecondColumnPanel.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        bathroomsLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        bathroomsLabel.setForeground(new java.awt.Color(255, 255, 255));
        bathroomsLabel.setText("Números de banheiros");
        propertySecondColumnPanel.add(bathroomsLabel);

        bathroomsComboBox.setBackground(new java.awt.Color(120, 120, 120));
        bathroomsComboBox.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        bathroomsComboBox.setForeground(new java.awt.Color(255, 255, 255));
        bathroomsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 Banheiros", "1 Banheiro", "2 Banheiros", "3 Banheiros", "+4 Banheiros" }));
        bathroomsComboBox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bathroomsComboBox.getEditor().getEditorComponent().setBackground(new java.awt.Color(120, 120, 120));
        bathroomsComboBox.getEditor().getEditorComponent().setForeground(new java.awt.Color(255, 255, 255));
        ((javax.swing.JComponent) bathroomsComboBox.getEditor().getEditorComponent()).setBorder(new javax.swing.border.EmptyBorder(0, 0, 0, 0));
        propertySecondColumnPanel.add(bathroomsComboBox);

        areaLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        areaLabel.setForeground(new java.awt.Color(255, 255, 255));
        areaLabel.setText("Área do imovel");
        propertySecondColumnPanel.add(areaLabel);

        areaTextField.setBackground(new java.awt.Color(120, 120, 120));
        areaTextField.setForeground(new java.awt.Color(255, 255, 255));
        areaTextField.setText("jNumberTextField1");
        areaTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        propertySecondColumnPanel.add(areaTextField);

        propertyPanel.add(propertySecondColumnPanel);

        propertyThirdColumnPanel.setOpaque(false);
        propertyThirdColumnPanel.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        valueLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(255, 255, 255));
        valueLabel.setText("Valor");
        propertyThirdColumnPanel.add(valueLabel);

        valueTextField.setBackground(new java.awt.Color(120, 120, 120));
        valueTextField.setForeground(new java.awt.Color(255, 255, 255));
        valueTextField.setText("jNumberTextField1");
        valueTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        propertyThirdColumnPanel.add(valueTextField);

        garageLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        garageLabel.setForeground(new java.awt.Color(255, 255, 255));
        garageLabel.setText("Garagem");
        propertyThirdColumnPanel.add(garageLabel);

        garageComboBox.setBackground(new java.awt.Color(120, 120, 120));
        garageComboBox.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        garageComboBox.setForeground(new java.awt.Color(255, 255, 255));
        garageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "1 Carro", "2 Carros", "3 Carros", "+4 Carros" }));
        garageComboBox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        garageComboBox.getEditor().getEditorComponent().setBackground(new java.awt.Color(120, 120, 120));
        garageComboBox.getEditor().getEditorComponent().setForeground(new java.awt.Color(255, 255, 255));
        ((javax.swing.JComponent) garageComboBox.getEditor().getEditorComponent()).setBorder(new javax.swing.border.EmptyBorder(0, 0, 0, 0));
        propertyThirdColumnPanel.add(garageComboBox);

        propertyPanel.add(propertyThirdColumnPanel);

        realEstatePanel.add(propertyPanel);

        bottomMenuPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        bottomMenuPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        bottomMenuPanel.setOpaque(false);
        bottomMenuPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        returnButton.setBackground(new java.awt.Color(40, 40, 80));
        returnButton.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        returnButton.setForeground(new java.awt.Color(255, 255, 255));
        returnButton.setText("Voltar");
        returnButton.setMaximumSize(new java.awt.Dimension(120, 25));
        returnButton.setMinimumSize(new java.awt.Dimension(120, 25));
        returnButton.setPreferredSize(new java.awt.Dimension(120, 25));
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        bottomMenuPanel.add(returnButton);

        deleteButton.setBackground(new java.awt.Color(40, 40, 80));
        deleteButton.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Deletar");
        deleteButton.setMaximumSize(new java.awt.Dimension(120, 25));
        deleteButton.setMinimumSize(new java.awt.Dimension(120, 25));
        deleteButton.setPreferredSize(new java.awt.Dimension(120, 25));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        bottomMenuPanel.add(deleteButton);

        saveButton.setBackground(new java.awt.Color(40, 40, 80));
        saveButton.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Salvar");
        saveButton.setMaximumSize(new java.awt.Dimension(120, 25));
        saveButton.setMinimumSize(new java.awt.Dimension(120, 25));
        saveButton.setPreferredSize(new java.awt.Dimension(120, 25));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        bottomMenuPanel.add(saveButton);

        realEstatePanel.add(bottomMenuPanel);

        backgroundPanel.add(realEstatePanel);

        rentalPanel.setBackground(new java.awt.Color(60, 60, 60));
        rentalPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        rentalPanel.setMinimumSize(new java.awt.Dimension(244, 650));
        rentalPanel.setPreferredSize(new java.awt.Dimension(476, 650));
        rentalPanel.setLayout(new java.awt.CardLayout());

        rentPanel.setBackground(new java.awt.Color(60, 60, 60));
        rentPanel.setMaximumSize(new java.awt.Dimension(32767, 600));
        rentPanel.setMinimumSize(new java.awt.Dimension(100, 100));
        rentPanel.setName(""); // NOI18N
        rentPanel.setPreferredSize(new java.awt.Dimension(456, 600));
        rentPanel.setLayout(new javax.swing.BoxLayout(rentPanel, javax.swing.BoxLayout.PAGE_AXIS));

        contractsTitlePanel.setOpaque(false);

        contractsTitleLabel.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        contractsTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        contractsTitleLabel.setText("Contratos");
        contractsTitlePanel.add(contractsTitleLabel);

        rentPanel.add(contractsTitlePanel);

        rentScrollPanel.setOpaque(false);
        rentScrollPanel.getViewport().setBackground(new java.awt.Color(40, 40, 40, 180));
        rentScrollPanel.getViewport().setBorder(null);

        rentTable.setFont(new java.awt.Font("Abyssinica SIL", 0, 16)); // NOI18N
        rentTable.setForeground(new java.awt.Color(255, 255, 255));
        rentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Data", "Vencimento", "Status", "Editar", "Aluguel"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rentTable.setRowHeight(25);
        rentTable.setOpaque(false);
        ((DefaultTableCellRenderer) rentTable.getDefaultRenderer(Object.class)).setBackground(new java.awt.Color(120, 120, 160, 180));
        ((DefaultTableCellRenderer) rentTable.getDefaultRenderer(Object.class)).setBorder(null);
        rentTable.getTableHeader().setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        rentTable.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        rentTable.getTableHeader().setBackground(new java.awt.Color(40, 40, 80, 255));
        rentTable.getTableHeader().setBorder(null);
        rentScrollPanel.setViewportView(rentTable);
        if (rentTable.getColumnModel().getColumnCount() > 0) {
            rentTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            rentTable.getColumnModel().getColumn(1).setPreferredWidth(80);
            rentTable.getColumnModel().getColumn(2).setPreferredWidth(80);
            rentTable.getColumnModel().getColumn(3).setPreferredWidth(80);
            rentTable.getColumnModel().getColumn(4).setPreferredWidth(80);
            rentTable.getColumnModel().getColumn(5).setPreferredWidth(80);
        }

        rentPanel.add(rentScrollPanel);

        actionPanel.setOpaque(false);

        openRentFormButton.setBackground(new java.awt.Color(40, 40, 80));
        openRentFormButton.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        openRentFormButton.setForeground(new java.awt.Color(255, 255, 255));
        openRentFormButton.setText("Cadastrar");
        openRentFormButton.setMaximumSize(new java.awt.Dimension(120, 25));
        openRentFormButton.setMinimumSize(new java.awt.Dimension(120, 25));
        openRentFormButton.setPreferredSize(new java.awt.Dimension(120, 25));
        openRentFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openRentFormButtonActionPerformed(evt);
            }
        });
        actionPanel.add(openRentFormButton);

        documentButton.setBackground(new java.awt.Color(40, 40, 80));
        documentButton.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        documentButton.setForeground(new java.awt.Color(255, 255, 255));
        documentButton.setText("Contrato");
        documentButton.setMaximumSize(new java.awt.Dimension(120, 25));
        documentButton.setMinimumSize(new java.awt.Dimension(120, 25));
        documentButton.setPreferredSize(new java.awt.Dimension(120, 25));
        documentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                documentButtonActionPerformed(evt);
            }
        });
        actionPanel.add(documentButton);

        rentPanel.add(actionPanel);

        rentalPanel.add(rentPanel, "rentContracts");

        rentFormPanel.setBackground(new java.awt.Color(60, 60, 60));

        rentFormPanel.setLayout(new javax.swing.BoxLayout(rentFormPanel, javax.swing.BoxLayout.PAGE_AXIS));

        titleRentRegisterPanel.setMaximumSize(new java.awt.Dimension(32767, 30));
        titleRentRegisterPanel.setMinimumSize(new java.awt.Dimension(137, 30));
        titleRentRegisterPanel.setOpaque(false);
        titleRentRegisterPanel.setPreferredSize(new java.awt.Dimension(137, 30));

        jLabel27.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Novo Contrato");
        titleRentRegisterPanel.add(jLabel27);

        rentFormPanel.add(titleRentRegisterPanel);

        peoplePanel.setOpaque(false);
        peoplePanel.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        landLordPanel.setOpaque(false);
        landLordPanel.setLayout(new java.awt.GridLayout(9, 0));

        landLordLabel.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        landLordLabel.setForeground(new java.awt.Color(255, 255, 255));
        landLordLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        landLordLabel.setText("Locador");
        landLordPanel.add(landLordLabel);

        landLordNameLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        landLordNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        landLordNameLabel.setText("Nome");
        landLordPanel.add(landLordNameLabel);

        landLordNameTextField.setBackground(new java.awt.Color(120, 120, 120));
        landLordNameTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        landLordNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        landLordNameTextField.setToolTipText("");
        landLordPanel.add(landLordNameTextField);

        landLordCPFLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        landLordCPFLabel.setForeground(new java.awt.Color(255, 255, 255));
        landLordCPFLabel.setText("CPF");
        landLordPanel.add(landLordCPFLabel);

        landLordCPFTextField.setBackground(new java.awt.Color(120, 120, 120));
        landLordCPFTextField.setForeground(new java.awt.Color(255, 255, 255));
        try {
            landLordCPFTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        landLordCPFTextField.setToolTipText("");
        landLordCPFTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        landLordPanel.add(landLordCPFTextField);

        landLordPhoneLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        landLordPhoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        landLordPhoneLabel.setText("Telefone");
        landLordPanel.add(landLordPhoneLabel);

        landLordPhoneTextField.setBackground(new java.awt.Color(120, 120, 120));
        landLordPhoneTextField.setForeground(new java.awt.Color(255, 255, 255));
        try {
            landLordPhoneTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        landLordPhoneTextField.setToolTipText("");
        landLordPhoneTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        landLordPanel.add(landLordPhoneTextField);

        landLordEmailLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        landLordEmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        landLordEmailLabel.setText("Email");
        landLordPanel.add(landLordEmailLabel);

        landLordEmailTextField.setBackground(new java.awt.Color(120, 120, 120));
        landLordEmailTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        landLordEmailTextField.setForeground(new java.awt.Color(255, 255, 255));
        landLordEmailTextField.setToolTipText("");
        landLordPanel.add(landLordEmailTextField);

        peoplePanel.add(landLordPanel);

        tenantPanel.setOpaque(false);
        tenantPanel.setLayout(new java.awt.GridLayout(9, 0));

        tenantLabel.setFont(new java.awt.Font("Abyssinica SIL", 1, 24)); // NOI18N
        tenantLabel.setForeground(new java.awt.Color(255, 255, 255));
        tenantLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tenantLabel.setText("Locatário");
        tenantPanel.add(tenantLabel);

        tenantNameLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        tenantNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        tenantNameLabel.setText("Nome");
        tenantPanel.add(tenantNameLabel);

        tenantNameTextField.setBackground(new java.awt.Color(120, 120, 120));
        tenantNameTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        tenantNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        tenantNameTextField.setToolTipText("");
        tenantPanel.add(tenantNameTextField);

        tenantCPFLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        tenantCPFLabel.setForeground(new java.awt.Color(255, 255, 255));
        tenantCPFLabel.setText("CPF");
        tenantPanel.add(tenantCPFLabel);

        tenantCPFTextField.setBackground(new java.awt.Color(120, 120, 120));
        tenantCPFTextField.setForeground(new java.awt.Color(255, 255, 255));
        try {
            tenantCPFTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tenantCPFTextField.setToolTipText("");
        tenantCPFTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        tenantPanel.add(tenantCPFTextField);

        tenantPhoneLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        tenantPhoneLabel.setForeground(new java.awt.Color(255, 255, 255));
        tenantPhoneLabel.setText("Telefone");
        tenantPanel.add(tenantPhoneLabel);

        tenantPhoneTextField.setBackground(new java.awt.Color(120, 120, 120));
        tenantPhoneTextField.setForeground(new java.awt.Color(255, 255, 255));
        try {
            tenantPhoneTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tenantPhoneTextField.setToolTipText("");
        tenantPhoneTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        tenantPanel.add(tenantPhoneTextField);

        tenantEmailLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        tenantEmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        tenantEmailLabel.setText("Email");
        tenantPanel.add(tenantEmailLabel);

        tenantEmailTextField.setBackground(new java.awt.Color(120, 120, 120));
        tenantEmailTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        tenantEmailTextField.setForeground(new java.awt.Color(255, 255, 255));
        tenantEmailTextField.setToolTipText("");
        tenantPanel.add(tenantEmailTextField);

        peoplePanel.add(tenantPanel);

        rentFormPanel.add(peoplePanel);

        contractPane.setOpaque(false);
        contractPane.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        contractFirstColumnPanel.setOpaque(false);
        contractFirstColumnPanel.setLayout(new java.awt.GridLayout(6, 0));

        contractDateLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        contractDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        contractDateLabel.setText("Data do Contrato");
        contractFirstColumnPanel.add(contractDateLabel);

        contractDateTextField.setBackground(new java.awt.Color(120, 120, 120));
        contractDateTextField.setForeground(new java.awt.Color(255, 255, 255));
        try {
            contractDateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        contractDateTextField.setToolTipText("");
        contractDateTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        contractFirstColumnPanel.add(contractDateTextField);

        paymentDayLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        paymentDayLabel.setForeground(new java.awt.Color(255, 255, 255));
        paymentDayLabel.setText("Dia do Pagamento");
        contractFirstColumnPanel.add(paymentDayLabel);

        paymentBaseDateTextField.setBackground(new java.awt.Color(120, 120, 120));
        paymentBaseDateTextField.setForeground(new java.awt.Color(255, 255, 255));
        paymentBaseDateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        paymentBaseDateTextField.setToolTipText("");
        paymentBaseDateTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        contractFirstColumnPanel.add(paymentBaseDateTextField);

        rentValueLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        rentValueLabel.setForeground(new java.awt.Color(255, 255, 255));
        rentValueLabel.setText("Valor do aluguel");
        rentValueLabel.setToolTipText("");
        contractFirstColumnPanel.add(rentValueLabel);

        rentValueTextField.setBackground(new java.awt.Color(120, 120, 120));
        rentValueTextField.setForeground(new java.awt.Color(255, 255, 255));
        rentValueTextField.setText("jNumberTextField1");
        rentValueTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        contractFirstColumnPanel.add(rentValueTextField);

        contractPane.add(contractFirstColumnPanel);

        contractSecondColumnPanel.setOpaque(false);
        contractSecondColumnPanel.setLayout(new java.awt.GridLayout(6, 0));

        durationLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        durationLabel.setForeground(new java.awt.Color(255, 255, 255));
        durationLabel.setText("Duração");
        contractSecondColumnPanel.add(durationLabel);

        durationTextField.setBackground(new java.awt.Color(120, 120, 120));
        durationTextField.setForeground(new java.awt.Color(255, 255, 255));
        durationTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        durationTextField.setToolTipText("");
        durationTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        contractSecondColumnPanel.add(durationTextField);

        statusLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        statusLabel.setForeground(new java.awt.Color(255, 255, 255));
        statusLabel.setText("Status");
        contractSecondColumnPanel.add(statusLabel);

        statusComboBox.setBackground(new java.awt.Color(120, 120, 120));
        statusComboBox.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        statusComboBox.setForeground(new java.awt.Color(255, 255, 255));
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Cancelado", "Vencido" }));
        statusComboBox.setToolTipText("");
        statusComboBox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        statusComboBox.getEditor().getEditorComponent().setBackground(new java.awt.Color(120, 120, 120));
        statusComboBox.getEditor().getEditorComponent().setForeground(new java.awt.Color(255, 255, 255));
        ((javax.swing.JComponent) statusComboBox.getEditor().getEditorComponent()).setBorder(new javax.swing.border.EmptyBorder(0, 0, 0, 0));
        contractSecondColumnPanel.add(statusComboBox);

        contractPane.add(contractSecondColumnPanel);

        rentFormPanel.add(contractPane);

        rentOptionsPanel.setOpaque(false);

        closeRentFormButton.setBackground(new java.awt.Color(40, 40, 80));
        closeRentFormButton.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        closeRentFormButton.setForeground(new java.awt.Color(255, 255, 255));
        closeRentFormButton.setText("Voltar");
        closeRentFormButton.setMaximumSize(new java.awt.Dimension(120, 25));
        closeRentFormButton.setMinimumSize(new java.awt.Dimension(120, 25));
        closeRentFormButton.setPreferredSize(new java.awt.Dimension(120, 25));
        closeRentFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeRentFormButtonActionPerformed(evt);
            }
        });
        rentOptionsPanel.add(closeRentFormButton);

        submitRentButton.setBackground(new java.awt.Color(40, 40, 80));
        submitRentButton.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        submitRentButton.setForeground(new java.awt.Color(255, 255, 255));
        submitRentButton.setText("Enviar");
        submitRentButton.setMaximumSize(new java.awt.Dimension(120, 25));
        submitRentButton.setMinimumSize(new java.awt.Dimension(120, 25));
        submitRentButton.setPreferredSize(new java.awt.Dimension(120, 25));
        submitRentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitRentButtonActionPerformed(evt);
            }
        });
        rentOptionsPanel.add(submitRentButton);

        rentFormPanel.add(rentOptionsPanel);

        rentalPanel.add(rentFormPanel, "rentForm");

        contractPanel.setOpaque(false);
        contractPanel.setLayout(new javax.swing.BoxLayout(contractPanel, javax.swing.BoxLayout.PAGE_AXIS));

        contractImagePanel.setMaximumSize(new java.awt.Dimension(350, 550));
        contractImagePanel.setMinimumSize(new java.awt.Dimension(350, 550));
        contractImagePanel.setOpaque(false);
        contractImagePanel.setPreferredSize(new java.awt.Dimension(350, 550));
        contractImagePanel.setLayout(new java.awt.BorderLayout());

        imageScrollPanel.setMaximumSize(new java.awt.Dimension(350, 550));
        imageScrollPanel.setMinimumSize(new java.awt.Dimension(350, 550));

        contractImageLabel.setMaximumSize(new java.awt.Dimension(32767, 32767));
        imageScrollPanel.add(contractImageLabel);

        contractImagePanel.add(imageScrollPanel, java.awt.BorderLayout.CENTER);

        contractPanel.add(contractImagePanel);

        contractMenuPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        contractMenuPanel.setMinimumSize(new java.awt.Dimension(255, 100));
        contractMenuPanel.setOpaque(false);

        returnRentsButton.setBackground(new java.awt.Color(40, 40, 80));
        returnRentsButton.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        returnRentsButton.setForeground(new java.awt.Color(255, 255, 255));
        returnRentsButton.setText("Voltar");
        returnRentsButton.setMaximumSize(new java.awt.Dimension(120, 25));
        returnRentsButton.setMinimumSize(new java.awt.Dimension(120, 25));
        returnRentsButton.setPreferredSize(new java.awt.Dimension(120, 25));
        returnRentsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnRentsButtonActionPerformed(evt);
            }
        });
        contractMenuPanel.add(returnRentsButton);

        changeDocumentButton.setBackground(new java.awt.Color(40, 40, 80));
        changeDocumentButton.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        changeDocumentButton.setForeground(new java.awt.Color(255, 255, 255));
        changeDocumentButton.setText("Substituir");
        changeDocumentButton.setMaximumSize(new java.awt.Dimension(120, 25));
        changeDocumentButton.setMinimumSize(new java.awt.Dimension(120, 25));
        changeDocumentButton.setPreferredSize(new java.awt.Dimension(120, 25));
        changeDocumentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeDocumentButtonActionPerformed(evt);
            }
        });
        contractMenuPanel.add(changeDocumentButton);

        downloadButton.setBackground(new java.awt.Color(40, 40, 80));
        downloadButton.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        downloadButton.setForeground(new java.awt.Color(255, 255, 255));
        downloadButton.setText("Download");
        downloadButton.setMaximumSize(new java.awt.Dimension(120, 25));
        downloadButton.setMinimumSize(new java.awt.Dimension(120, 25));
        downloadButton.setPreferredSize(new java.awt.Dimension(120, 25));
        downloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadButtonActionPerformed(evt);
            }
        });
        contractMenuPanel.add(downloadButton);

        contractPanel.add(contractMenuPanel);

        rentalPanel.add(contractPanel, "contractImage");

        backgroundPanel.add(rentalPanel);

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 650));
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            realEstateController.deleteProperty(this.propertyId);
            JOptionPane.showMessageDialog(null, "Imóvel deletado com sucesso");
            dispose();
        } catch (Exception e) {
            System.err.println(e);
            dispose();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            areaTextField.setBackground(new Color(120, 120, 120));
            valueTextField.setBackground(new Color(120, 120, 120));
            
            if (addressTextField.getText().length() == 0) {
                addressTextField.setBackground(Color.RED);
                addressTextField.setToolTipText("Campo obrigatório");
                System.err.println("Required field");
                return;
            }
            
            if (neighborhoodTextField.getText().length() == 0) {
                neighborhoodTextField.setBackground(Color.RED);
                neighborhoodTextField.setToolTipText("Campo obrigatório");
                System.err.println("Required field");
                return;
            }
            
            if (cityTextField.getText().length() == 0) {
                cityTextField.setBackground(Color.RED);
                cityTextField.setToolTipText("Campo obrigatório");
                System.err.println("Required field");
                return;
            }
            
            if (!isValidDouble(areaTextField.getText().replace(",", "."))) {
                areaTextField.setBackground(Color.RED);
                areaTextField.setToolTipText("Valor invalido, formato: 0,00");
                System.err.println("Invalid area value");
                return;
            }
            
            if (!isValidDouble(valueTextField.getText().replace(",", "."))) {
                valueTextField.setBackground(Color.RED);
                valueTextField.setToolTipText("Valor invalido, formato: 0,00");
                System.err.println("Invalid value");
                return;
            }
            
            RealEstateModel realEstate = new RealEstateModel(
                this.propertyId,
                addressTextField.getText(),
                neighborhoodTextField.getText(),
                numberTextField.getText(),
                cityTextField.getText(),
                typeComboBox.getSelectedItem().toString(),
                roomsComboBox.getSelectedIndex(),
                bathroomsComboBox.getSelectedIndex(),
                Double.valueOf(areaTextField.getText().replace(",", ".")),
                Double.valueOf(valueTextField.getText().replace(",", ".")),
                garageComboBox.getSelectedIndex()
            );
            
            realEstateController.updateProperty(realEstate);
            
            JOptionPane.showMessageDialog(null, "Imóvel atualizado com sucesso");
        } catch(Exception e) {
            System.err.println("Error: " + e);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void openRentFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openRentFormButtonActionPerformed
        this.rentalCardLayout.show(rentalPanel, "rentForm");

        contractDateTextField.setText("");
        paymentBaseDateTextField.setText("");
        rentValueTextField.setText("");
        landLordNameTextField.setText("");
        landLordCPFTextField.setText("");
        landLordPhoneTextField.setText("");
        landLordEmailTextField.setText("");
        tenantNameTextField.setText("");
        tenantCPFTextField.setText("");
        tenantPhoneTextField.setText("");
        tenantEmailTextField.setText("");
        durationTextField.setText("");
        statusComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_openRentFormButtonActionPerformed

    private void closeRentFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeRentFormButtonActionPerformed
        this.rentalCardLayout.show(rentalPanel, "rentContracts");
    }//GEN-LAST:event_closeRentFormButtonActionPerformed

    private void submitRentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitRentButtonActionPerformed
        try {
            paymentBaseDateTextField.setBackground(new Color(120, 120, 120));
            durationTextField.setBackground(new Color(120, 120, 120));
            rentValueTextField.setBackground(new Color(120, 120, 120));
            contractDateTextField.setBackground(new Color(120, 120, 120));
            
            if (!isValidInteger(paymentBaseDateTextField.getText()) ||
                Integer.parseInt(paymentBaseDateTextField.getText()) < 1 ||
                Integer.parseInt(paymentBaseDateTextField.getText()) > 28) {
                paymentBaseDateTextField.setBackground(Color.RED);
                paymentBaseDateTextField.setToolTipText("Campo númerico entre 1 e 28");
                System.err.println("Payment day field must be an integer");
                return;
            }
            
            if (!isValidInteger(durationTextField.getText())) {
                durationTextField.setBackground(Color.RED);
                durationTextField.setToolTipText("Campo númerico");
                System.err.println("Duration field must be an integer");
                return;
            }
            
            if (!isValidDouble(rentValueTextField.getText())) {
                rentValueTextField.setBackground(Color.RED);
                rentValueTextField.setToolTipText("Campo númerico, use o formato 0,00");
                System.err.println("Rent Value field must be a double");
                return;
            }
            
            if (contractDateTextField.getText() == "  /    ") {
                contractDateTextField.setBackground(Color.RED);
                contractDateTextField.setToolTipText("Campo data, use o formato ##/####");
                System.err.println("Contract Date must have format ##/####");
                return;
            }
            
            int paymentDay = Integer.parseInt(paymentBaseDateTextField.getText());
            int duration = Integer.parseInt(durationTextField.getText());
            double rentValue = Double.parseDouble(rentValueTextField.getText());
            
            String[] contractDateParts = contractDateTextField.getText().split("/");
            String dueDate = addMonthsToDate("01/" + contractDateTextField.getText(), duration);
            String[] dueDateParts = dueDate.split("/");
            
            RentalModel rental = new RentalModel(
                Integer.valueOf(contractDateParts[0]),
                Integer.valueOf(contractDateParts[1]),
                paymentDay,
                rentValue,
                landLordNameTextField.getText(),
                landLordCPFTextField.getText(),
                landLordPhoneTextField.getText(),
                landLordEmailTextField.getText(),
                tenantNameTextField.getText(),
                tenantCPFTextField.getText(),
                tenantPhoneTextField.getText(),
                tenantEmailTextField.getText(),
                duration,
                Integer.valueOf(dueDateParts[1]),
                Integer.valueOf(dueDateParts[2]),
                this.propertyId,
                statusComboBox.getSelectedItem().toString(),
                ""
            );
            
            if (this.rentFormStatus.equals("Register")) {
                rentalController.addRental(rental);
            } else {
                rental.setId(this.rentalId);
                rentalController.updateRental(rental);
            }
            
            updateTable();
            this.rentalCardLayout.show(rentalPanel, "rentContracts");
            
            JOptionPane.showMessageDialog(null, "Aluguel cadastrado/editado com sucesso");
        } catch(Exception e) {
            System.err.println("Error: " + e);
        }
    }//GEN-LAST:event_submitRentButtonActionPerformed

    private void documentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_documentButtonActionPerformed
        int row = rentTable.getSelectedRow();
        if (row == -1) return;
        
        String id = String.valueOf(rentTable.getValueAt(row, 0));
        
        selectedRent = rentalController.getRentalById(Integer.parseInt(id));
        
        if (selectedRent.getContract() == null) {
            this.addDocument(id);
        } else {
            this.rentalCardLayout.show(rentalPanel, "contractImage");
            this.loadContract(selectedRent.getContract());
        }
    }//GEN-LAST:event_documentButtonActionPerformed
    
    private void returnRentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnRentsButtonActionPerformed
        this.rentalCardLayout.show(rentalPanel, "rentContracts");
    }//GEN-LAST:event_returnRentsButtonActionPerformed

    private void changeDocumentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeDocumentButtonActionPerformed
        this.addDocument(String.valueOf(selectedRent.getId()));
        
    }//GEN-LAST:event_changeDocumentButtonActionPerformed

    private void downloadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadButtonActionPerformed

        if (selectedRent.getContract() == null) return;

        String extention = getFileExtension(selectedRent.getContract());

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Onde deseja salvar o arquivo?");
        fileChooser.setSelectedFile(new File("contrato." + extention));

        int userSelection = fileChooser.showSaveDialog(this);
        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File saveFile = fileChooser.getSelectedFile();
            try {
                Files.copy(new File(selectedRent.getContract()).toPath(), saveFile.toPath());
                JOptionPane.showMessageDialog(this, "Contrato baixado com sucesso.");
            } catch (Exception ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_downloadButtonActionPerformed

    public void addDocument(String id) {
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            
            String extension = getFileExtension(selectedFile.getName());
  
            File internalStorage = new File("internal_storage/contracts");
            if (!internalStorage.exists()) {
                internalStorage.mkdirs();
            }
            
            File destFile = new File(internalStorage, id + "." + extension);

            try (InputStream in = new FileInputStream(selectedFile);
                 OutputStream out = new FileOutputStream(destFile)) {

                byte[] buffer = new byte[1024];
                int length;
                while ((length = in.read(buffer)) > 0) {
                    out.write(buffer, 0, length);
                }
                
                rentalController.addContract(Integer.parseInt(id), destFile.getAbsolutePath());
                JOptionPane.showMessageDialog(null, "Contrato salvo com sucesso");
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }
    
    public void loadContract(String contractPath) {
        String extension = getFileExtension(contractPath).toLowerCase();
        
        switch (extension) {
            case "jpg":
            case "jpeg":
            case "png":
                ImageIcon contractImage = new ImageIcon(contractPath);
                contractImageLabel.setIcon(contractImage);
                break;
            case "pdf":
                try {
                    File file = new File(contractPath);
                    PDDocument document = PDDocument.load(file);
                    PDFRenderer renderer = new PDFRenderer(document);

                    BufferedImage contractPageBuffer = renderer.renderImageWithDPI(0, 150);
                    
                    ImageIcon defaultImage = new ImageIcon(contractPageBuffer);
                    contractImageLabel.setIcon(defaultImage);
                } catch (Exception ex) {
                    ex.printStackTrace();
                    ImageIcon defaultImage = new ImageIcon(getClass().getResource("/static/icons/documentNotSupported.png"));
                    contractImageLabel.setIcon(defaultImage);
                }
                break;
            default:
                ImageIcon defaultImage = new ImageIcon(getClass().getResource("/static/icons/documentNotSupported.png"));
                contractImageLabel.setIcon(defaultImage);
                break;
        }
    }
    
    public String getFileExtension(String filePath) {
        int dotIndex = filePath.lastIndexOf('.');
        return (dotIndex == -1) ? "" : filePath.substring(dotIndex + 1);
    }
    
    public void openUpdateForm(int rentalId) {
        this.rentalCardLayout.show(rentalPanel, "rentForm");
        this.rentalId = rentalId;
        this.rentFormStatus = "Update";
        

        RentalModel rental = rentalController.getRentalById(rentalId);
        
        String rentValue = String.valueOf(rental.getRentValue());
        
        contractDateTextField.setText(String.format("%02d/%04d", rental.getContractMonth(), rental.getContractYear()));
        paymentBaseDateTextField.setText(String.valueOf(rental.getPaymentBaseDate()));
        rentValueTextField.setText(rentValue);
        landLordNameTextField.setText(rental.getLandlordName());
        landLordCPFTextField.setText(rental.getLandlordCpf());
        landLordPhoneTextField.setText(rental.getLandlordPhone());
        landLordEmailTextField.setText(rental.getLandlordEmail());
        tenantNameTextField.setText(rental.getTenantName());
        tenantCPFTextField.setText(rental.getTenantCpf());
        tenantPhoneTextField.setText(rental.getTenantPhone());
        tenantEmailTextField.setText(rental.getTenantEmail());
        durationTextField.setText(String.valueOf(rental.getDurationMonths()));
        statusComboBox.setSelectedItem(rental.getStatus());
    }
    
    public void updateTable() {        
        DefaultTableModel tableModel = (DefaultTableModel) rentTable.getModel();
        tableModel.setRowCount(0);
        
        for (RentalModel rental : rentalController.getAllRentalsByPropertyId(this.propertyId)) {
            Object[] row = {
                rental.getId(),
                String.format("%02d/%04d", rental.getContractMonth(), rental.getContractYear()),
                String.format("%02d/%04d", rental.getDueMonth(), rental.getDueYear()),
                rental.getStatus(),
                "",
                "",
            };
            tableModel.addRow(row);
        }
        
        rentTable.repaint();
        rentTable.getParent().repaint();
    }
    
    private boolean isValidInteger(String input) {
        try {
            Integer.parseInt(input);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    private boolean isValidDouble(String input) {
        try {
            Double.parseDouble(input);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }


    public static String addMonthsToDate(String dateStr, int monthsToAdd) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate date = LocalDate.parse(dateStr, formatter);
        LocalDate updatedDate = date.plusMonths(monthsToAdd);
        return updatedDate.format(formatter);
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(int id, String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealEstate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealEstate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealEstate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealEstate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealEstate(id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JPanel addressFirstColumnPanel;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JPanel addressPanel;
    private javax.swing.JPanel addressSecondColumnPanel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JLabel areaLabel;
    private com.mycompany.imobiliaria.views.components.JNumberTextField areaTextField;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JComboBox<String> bathroomsComboBox;
    private javax.swing.JLabel bathroomsLabel;
    private javax.swing.JPanel bottomMenuPanel;
    private javax.swing.JButton changeDocumentButton;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JButton closeRentFormButton;
    private javax.swing.JLabel contractDateLabel;
    private javax.swing.JFormattedTextField contractDateTextField;
    private javax.swing.JPanel contractFirstColumnPanel;
    private javax.swing.JLabel contractImageLabel;
    private javax.swing.JPanel contractImagePanel;
    private javax.swing.JPanel contractMenuPanel;
    private javax.swing.JPanel contractPane;
    private javax.swing.JPanel contractPanel;
    private javax.swing.JPanel contractSecondColumnPanel;
    private javax.swing.JLabel contractsTitleLabel;
    private javax.swing.JPanel contractsTitlePanel;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton documentButton;
    private javax.swing.JButton downloadButton;
    private javax.swing.JLabel durationLabel;
    private javax.swing.JFormattedTextField durationTextField;
    private javax.swing.JComboBox<String> garageComboBox;
    private javax.swing.JLabel garageLabel;
    private java.awt.ScrollPane imageScrollPanel;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel landLordCPFLabel;
    private javax.swing.JFormattedTextField landLordCPFTextField;
    private javax.swing.JLabel landLordEmailLabel;
    private javax.swing.JTextField landLordEmailTextField;
    private javax.swing.JLabel landLordLabel;
    private javax.swing.JLabel landLordNameLabel;
    private javax.swing.JTextField landLordNameTextField;
    private javax.swing.JPanel landLordPanel;
    private javax.swing.JLabel landLordPhoneLabel;
    private javax.swing.JFormattedTextField landLordPhoneTextField;
    private javax.swing.JLabel neighborhoodLabel;
    private javax.swing.JTextField neighborhoodTextField;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JButton openRentFormButton;
    private javax.swing.JFormattedTextField paymentBaseDateTextField;
    private javax.swing.JLabel paymentDayLabel;
    private javax.swing.JPanel peoplePanel;
    private javax.swing.JPanel propertyFirstColumnPanel;
    private javax.swing.JPanel propertyPanel;
    private javax.swing.JPanel propertySecondColumnPanel;
    private javax.swing.JPanel propertyThirdColumnPanel;
    private javax.swing.JPanel realEstatePanel;
    private javax.swing.JPanel rentFormPanel;
    private javax.swing.JPanel rentOptionsPanel;
    private javax.swing.JPanel rentPanel;
    private javax.swing.JScrollPane rentScrollPanel;
    private javax.swing.JTable rentTable;
    private javax.swing.JLabel rentValueLabel;
    private com.mycompany.imobiliaria.views.components.JNumberTextField rentValueTextField;
    private javax.swing.JPanel rentalPanel;
    private javax.swing.JButton returnButton;
    private javax.swing.JButton returnRentsButton;
    private javax.swing.JComboBox<String> roomsComboBox;
    private javax.swing.JLabel roomsLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JButton submitRentButton;
    private javax.swing.JLabel tenantCPFLabel;
    private javax.swing.JFormattedTextField tenantCPFTextField;
    private javax.swing.JLabel tenantEmailLabel;
    private javax.swing.JTextField tenantEmailTextField;
    private javax.swing.JLabel tenantLabel;
    private javax.swing.JLabel tenantNameLabel;
    private javax.swing.JTextField tenantNameTextField;
    private javax.swing.JPanel tenantPanel;
    private javax.swing.JLabel tenantPhoneLabel;
    private javax.swing.JFormattedTextField tenantPhoneTextField;
    private javax.swing.JPanel titleRentRegisterPanel;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JLabel typeLabel;
    private javax.swing.JLabel valueLabel;
    private com.mycompany.imobiliaria.views.components.JNumberTextField valueTextField;
    // End of variables declaration//GEN-END:variables
}

class RentalButtonRenderer extends JButton implements TableCellRenderer {
    public RentalButtonRenderer() {
        setToolTipText("Editar");

        ImageIcon pencilIcon = new ImageIcon(getClass().getResource("/static/icons/edit.png"));
        setIcon(pencilIcon);

        setText("");

        setHorizontalAlignment(SwingConstants.CENTER);
        setBorderPainted(false);
        setContentAreaFilled(false);
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
        boolean isSelected, boolean hasFocus, int row, int column) {
        return this;
    }
}

class PaymentButtonRenderer extends JButton implements TableCellRenderer {
    public PaymentButtonRenderer() {
        setToolTipText("Editar");

        ImageIcon pencilIcon = new ImageIcon(getClass().getResource("/static/icons/wallet.png"));
        setIcon(pencilIcon);

        setText("");

        setHorizontalAlignment(SwingConstants.CENTER);
        setBorderPainted(false);
        setContentAreaFilled(false);
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
        boolean isSelected, boolean hasFocus, int row, int column) {
        return this;
    }
}

class RentalButtonEditor extends DefaultCellEditor {
    private JButton button;
    private boolean isPushed;
    private JTable table;
    private JFrame mainFrame;

    public RentalButtonEditor(JCheckBox checkBox, JTable table, JFrame mainFrame) {
        super(checkBox);
        this.table = table;
        this.mainFrame = mainFrame;
        button = new JButton("");
        button.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                fireEditingStopped();
                int selectedRow = table.getSelectedRow();
                Object idValue = table.getValueAt(selectedRow, 0);
                openDetailsWindow(idValue);
            }
        });
    }

    @Override
    public Component getTableCellEditorComponent(JTable table, Object value,
        boolean isSelected, int row, int column) {
        isPushed = true;
        return button;
    }

    @Override
    public boolean stopCellEditing() {
        isPushed = false;
        return super.stopCellEditing();
    }

    private void openDetailsWindow(Object idObj) {
        int id = Integer.parseInt(idObj.toString());
        
        if (mainFrame instanceof RealEstate) {
            ((RealEstate) mainFrame).openUpdateForm(id);
        }
    }
}

class PaymentButtonEditor extends DefaultCellEditor {
    private JButton button;
    private boolean isPushed;
    private JTable table;
    private PaymentRegister paymentRegisterFrame = null;

    public PaymentButtonEditor(JCheckBox checkBox, JTable table) {
        super(checkBox);
        this.table = table;
        button = new JButton("");
        button.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                fireEditingStopped();
                int selectedRow = table.getSelectedRow();
                Object idValue = table.getValueAt(selectedRow, 0);
                openDetailsWindow(idValue);
            }
        });
    }

    @Override
    public Component getTableCellEditorComponent(JTable table, Object value,
        boolean isSelected, int row, int column) {
        isPushed = true;
        return button;
    }

    @Override
    public boolean stopCellEditing() {
        isPushed = false;
        return super.stopCellEditing();
    }

    private void openDetailsWindow(Object idObj) {
        int id = Integer.parseInt(idObj.toString());
        
         if (paymentRegisterFrame == null || !paymentRegisterFrame.isDisplayable()) {
            paymentRegisterFrame = new PaymentRegister(id);
            paymentRegisterFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            paymentRegisterFrame.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    paymentRegisterFrame = null;
                }
            });
            
            paymentRegisterFrame.setVisible(true);
        } else {
            paymentRegisterFrame.toFront();
            paymentRegisterFrame.requestFocus();
            paymentRegisterFrame.setState(JFrame.NORMAL);
        }
    }
}
