/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.imobiliaria.views;

import com.mycompany.imobiliaria.controllers.RealEstateController;
import com.mycompany.imobiliaria.controllers.RentalController;
import com.mycompany.imobiliaria.models.RealEstateModel;
import com.mycompany.imobiliaria.models.RentalModel;
import com.mycompany.imobiliaria.views.PaymentRegister;

import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author user
 */
public class RealEstate extends javax.swing.JFrame {
    private static final RealEstateController realEstateController = new RealEstateController();
    private static final RentalController rentalController = new RentalController();
    private String rentFormStatus = "Register";
    private int propertyId;
    
    /**
     * Creates new form RealEstate
     * @param propertyId
     */
    public RealEstate(int propertyId) {
        initComponents();
        
        rentalFormPanel.setVisible(false);
        updateTable();
        
        try {
            RealEstateModel realEstate = realEstateController.getPropertyById(propertyId);
            
            this.propertyId = propertyId;
            addressTextField.setText(realEstate.getAddress());
            numberTextField.setText(realEstate.getNumber());
            neighborhoodTextField.setText(realEstate.getNeighborhood());
            cityTextField.setText(realEstate.getCity());
            areaTextField.setText(String.valueOf(realEstate.getArea()));
            valueTextField.setText(String.valueOf(realEstate.getValue()));
            typeComboBox.setSelectedItem(realEstate.getType());
            roomsComboBox.setSelectedIndex(realEstate.getRooms());
            bathroomsComboBox.setSelectedIndex(realEstate.getBathrooms());
            garageComboBox.setSelectedIndex(realEstate.getGarage());
        } catch (Exception e) {
            System.err.println(e);
            dispose();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        realEstatePanel = new javax.swing.JPanel();
        addressPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        neighborhoodTextField = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        numberTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        propertyPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        roomsComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bathroomsComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        areaTextField = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        valueTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        garageComboBox = new javax.swing.JComboBox<>();
        bottomMenuPanel = new javax.swing.JPanel();
        returnButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        rentalPanel = new javax.swing.JPanel();
        rentalsPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        rentTable = new javax.swing.JTable();
        actionPanel = new javax.swing.JPanel();
        openRentFormButton = new javax.swing.JButton();
        rentalFormPanel = new javax.swing.JPanel();
        peoplePanel = new javax.swing.JPanel();
        landLordPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        landLordNameTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        landLordCPFTextField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        landLordPhoneTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        landLordEmailTextField = new javax.swing.JTextField();
        tenantPanel = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        tenantNameTextField = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tenantCPFTextField = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tenantPhoneTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        tenantEmailTextField = new javax.swing.JTextField();
        contractPane = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        contractDateTextField = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        paymentBaseDateTextField = new javax.swing.JFormattedTextField();
        jLabel23 = new javax.swing.JLabel();
        rentValueTextField = new javax.swing.JFormattedTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        durationTextField = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        statusComboBox = new javax.swing.JComboBox<>();
        rentOptionsPanel = new javax.swing.JPanel();
        closeRentFormButton = new javax.swing.JButton();
        submitRentButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 500));
        setPreferredSize(new java.awt.Dimension(1000, 500));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        realEstatePanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 0, 10));
        realEstatePanel.setMinimumSize(new java.awt.Dimension(600, 600));
        realEstatePanel.setPreferredSize(new java.awt.Dimension(600, 600));
        realEstatePanel.setLayout(new javax.swing.BoxLayout(realEstatePanel, javax.swing.BoxLayout.PAGE_AXIS));

        addressPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        addressPanel.setOpaque(false);
        addressPanel.setLayout(new java.awt.GridLayout(1, 2, 25, 0));

        jPanel3.setOpaque(false);
        jPanel3.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jLabel1.setText("Endereço:");
        jPanel3.add(jLabel1);
        jPanel3.add(addressTextField);

        jLabel2.setText("Bairro");
        jPanel3.add(jLabel2);
        jPanel3.add(neighborhoodTextField);

        addressPanel.add(jPanel3);

        jPanel4.setOpaque(false);
        jPanel4.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jLabel3.setText("Número:");
        jPanel4.add(jLabel3);
        jPanel4.add(numberTextField);

        jLabel4.setText("Cidade");
        jPanel4.add(jLabel4);
        jPanel4.add(cityTextField);

        addressPanel.add(jPanel4);

        realEstatePanel.add(addressPanel);

        propertyPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 25, 0));
        propertyPanel.setOpaque(false);
        propertyPanel.setLayout(new java.awt.GridLayout(1, 3, 25, 0));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jLabel5.setText("Tipo");
        jPanel1.add(jLabel5);

        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Terreno", "Apartamento", "Chácara" }));
        jPanel1.add(typeComboBox);

        jLabel6.setText("Números de quartos");
        jPanel1.add(jLabel6);

        roomsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 Quartos", "1 Quarto", "2 Quartos", "3 Quartos", "+4 Quartos" }));
        jPanel1.add(roomsComboBox);

        propertyPanel.add(jPanel1);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jLabel7.setText("Números de banheiros");
        jPanel2.add(jLabel7);

        bathroomsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 Banheiros", "1 Banheiro", "2 Banheiros", "3 Banheiros", "+4 Banheiros" }));
        jPanel2.add(bathroomsComboBox);

        jLabel8.setText("Área do imovel");
        jPanel2.add(jLabel8);
        jPanel2.add(areaTextField);

        propertyPanel.add(jPanel2);

        jPanel5.setOpaque(false);
        jPanel5.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jLabel9.setText("Valor");
        jPanel5.add(jLabel9);
        jPanel5.add(valueTextField);

        jLabel10.setText("Garagem");
        jPanel5.add(jLabel10);

        garageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "1 Carro", "2 Carros", "3 Carros", "+4 Carros" }));
        jPanel5.add(garageComboBox);

        propertyPanel.add(jPanel5);

        realEstatePanel.add(propertyPanel);

        bottomMenuPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        bottomMenuPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        bottomMenuPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        returnButton.setText("Voltar");
        returnButton.setPreferredSize(new java.awt.Dimension(100, 30));
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });
        bottomMenuPanel.add(returnButton);

        deleteButton.setText("Deletar");
        deleteButton.setPreferredSize(new java.awt.Dimension(100, 30));
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });
        bottomMenuPanel.add(deleteButton);

        saveButton.setText("Atualizar");
        saveButton.setPreferredSize(new java.awt.Dimension(100, 30));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        bottomMenuPanel.add(saveButton);

        realEstatePanel.add(bottomMenuPanel);

        getContentPane().add(realEstatePanel);

        rentalPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        rentalPanel.setLayout(new javax.swing.BoxLayout(rentalPanel, javax.swing.BoxLayout.PAGE_AXIS));

        rentalsPanel.setLayout(new javax.swing.BoxLayout(rentalsPanel, javax.swing.BoxLayout.PAGE_AXIS));

        rentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(rentTable);

        rentalsPanel.add(jScrollPane1);

        openRentFormButton.setText("Cadastrar");
        openRentFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openRentFormButtonActionPerformed(evt);
            }
        });
        actionPanel.add(openRentFormButton);

        rentalsPanel.add(actionPanel);

        rentalPanel.add(rentalsPanel);

        rentalFormPanel.setLayout(new javax.swing.BoxLayout(rentalFormPanel, javax.swing.BoxLayout.PAGE_AXIS));

        peoplePanel.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        landLordPanel.setLayout(new java.awt.GridLayout(9, 0));

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Locador");
        landLordPanel.add(jLabel11);

        jLabel15.setText("Nome");
        landLordPanel.add(jLabel15);
        landLordPanel.add(landLordNameTextField);

        jLabel12.setText("CPF");
        landLordPanel.add(jLabel12);
        landLordPanel.add(landLordCPFTextField);

        jLabel13.setText("Telefone");
        landLordPanel.add(jLabel13);
        landLordPanel.add(landLordPhoneTextField);

        jLabel14.setText("Email");
        landLordPanel.add(jLabel14);
        landLordPanel.add(landLordEmailTextField);

        peoplePanel.add(landLordPanel);

        tenantPanel.setLayout(new java.awt.GridLayout(9, 0));

        jLabel16.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Locatário");
        tenantPanel.add(jLabel16);

        jLabel17.setText("Nome");
        tenantPanel.add(jLabel17);
        tenantPanel.add(tenantNameTextField);

        jLabel18.setText("CPF");
        tenantPanel.add(jLabel18);
        tenantPanel.add(tenantCPFTextField);

        jLabel19.setText("Telefone");
        tenantPanel.add(jLabel19);
        tenantPanel.add(tenantPhoneTextField);

        jLabel20.setText("Email");
        tenantPanel.add(jLabel20);
        tenantPanel.add(tenantEmailTextField);

        peoplePanel.add(tenantPanel);

        rentalFormPanel.add(peoplePanel);

        contractPane.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        jPanel6.setLayout(new java.awt.GridLayout(6, 0));

        jLabel24.setText("Data do Contrato");
        jPanel6.add(jLabel24);

        contractDateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jPanel6.add(contractDateTextField);

        jLabel21.setText("Dia do Pagamento");
        jPanel6.add(jLabel21);

        paymentBaseDateTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        jPanel6.add(paymentBaseDateTextField);

        jLabel23.setText("Valor do aluguel");
        jPanel6.add(jLabel23);

        rentValueTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        jPanel6.add(rentValueTextField);

        contractPane.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(6, 0));

        jLabel22.setText("Duração");
        jPanel7.add(jLabel22);

        durationTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        jPanel7.add(durationTextField);

        jLabel25.setText("Status");
        jPanel7.add(jLabel25);

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Cancelado", "Vencido" }));
        jPanel7.add(statusComboBox);

        contractPane.add(jPanel7);

        rentalFormPanel.add(contractPane);

        closeRentFormButton.setText("Voltar");
        closeRentFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeRentFormButtonActionPerformed(evt);
            }
        });
        rentOptionsPanel.add(closeRentFormButton);

        submitRentButton.setText("Enviar");
        submitRentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitRentButtonActionPerformed(evt);
            }
        });
        rentOptionsPanel.add(submitRentButton);

        rentalFormPanel.add(rentOptionsPanel);

        rentalPanel.add(rentalFormPanel);

        getContentPane().add(rentalPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        try {
            realEstateController.deleteProperty(this.propertyId);
            JOptionPane.showMessageDialog(null, "Imóvel deletado com sucesso");
            dispose();
        } catch (Exception e) {
            System.err.println(e);
            dispose();
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        dispose();
    }//GEN-LAST:event_returnButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            areaTextField.setBackground(Color.WHITE);
            valueTextField.setBackground(Color.WHITE);
            
            if (addressTextField.getText().length() == 0) {
                addressTextField.setBackground(Color.RED);
                addressTextField.setToolTipText("Campo obrigatório");
                System.out.println("Required field");
                return;
            }
            
            if (neighborhoodTextField.getText().length() == 0) {
                neighborhoodTextField.setBackground(Color.RED);
                neighborhoodTextField.setToolTipText("Campo obrigatório");
                System.out.println("Required field");
                return;
            }
            
            if (cityTextField.getText().length() == 0) {
                cityTextField.setBackground(Color.RED);
                cityTextField.setToolTipText("Campo obrigatório");
                System.out.println("Required field");
                return;
            }
            
            if (!isValidDouble(areaTextField.getText().replace(",", "."))) {
                areaTextField.setBackground(Color.RED);
                areaTextField.setToolTipText("Valor invalido, formato: 0,00");
                System.out.println("Invalid area value");
                return;
            }
            
            if (!isValidDouble(valueTextField.getText().replace(",", "."))) {
                valueTextField.setBackground(Color.RED);
                valueTextField.setToolTipText("Valor invalido, formato: 0,00");
                System.out.println("Invalid value");
                return;
            }
            
            RealEstateModel realEstate = new RealEstateModel(
                this.propertyId,
                addressTextField.getText(),
                neighborhoodTextField.getText(),
                numberTextField.getText(),
                cityTextField.getText(),
                typeComboBox.getSelectedItem().toString(),
                roomsComboBox.getSelectedIndex(),
                bathroomsComboBox.getSelectedIndex(),
                Double.valueOf(areaTextField.getText().replace(",", ".")),
                Double.valueOf(valueTextField.getText().replace(",", ".")),
                garageComboBox.getSelectedIndex()
            );
            
            realEstateController.updateProperty(realEstate);
            
            JOptionPane.showMessageDialog(null, "Imóvel atualizado com sucesso");
            dispose();
        } catch(Exception e) {
            System.out.println("Error: " + e);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void openRentFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openRentFormButtonActionPerformed
        rentalsPanel.setVisible(false);
        rentalFormPanel.setVisible(true);
        rentFormStatus = "Register";
    }//GEN-LAST:event_openRentFormButtonActionPerformed

    private void closeRentFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeRentFormButtonActionPerformed
        rentalsPanel.setVisible(true);
        rentalFormPanel.setVisible(false);
    }//GEN-LAST:event_closeRentFormButtonActionPerformed

    private void submitRentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitRentButtonActionPerformed
        try {
            if (!isValidInteger(paymentBaseDateTextField.getText()) ||
                Integer.parseInt(paymentBaseDateTextField.getText()) < 1 ||
                Integer.parseInt(paymentBaseDateTextField.getText()) > 28) {
                paymentBaseDateTextField.setBackground(Color.RED);
                paymentBaseDateTextField.setToolTipText("Campo númerico entre 1 e 28");
                System.out.println("Payment day field must be an integer");
                return;
            }
            
            if (!isValidInteger(durationTextField.getText())) {
                durationTextField.setBackground(Color.RED);
                durationTextField.setToolTipText("Campo númerico");
                System.out.println("Duration field must be an integer");
                return;
            }
            
            if (!isValidDouble(rentValueTextField.getText())) {
                rentValueTextField.setBackground(Color.RED);
                rentValueTextField.setToolTipText("Campo númerico, use o formato 0,00");
                System.out.println("Duration field must be a double");
                return;
            }
            
            int paymentDay = Integer.parseInt(paymentBaseDateTextField.getText());
            int duration = Integer.parseInt(durationTextField.getText());
            double rentValue = Double.parseDouble(rentValueTextField.getText());
            RentalModel rental = new RentalModel(
                contractDateTextField.getText(),
                paymentDay,
                rentValue,
                landLordNameTextField.getText(),
                landLordCPFTextField.getText(),
                landLordPhoneTextField.getText(),
                landLordEmailTextField.getText(),
                tenantNameTextField.getText(),
                tenantCPFTextField.getText(),
                tenantPhoneTextField.getText(),
                tenantEmailTextField.getText(),
                duration,
                addMonthsToDate(contractDateTextField.getText(), duration),
                this.propertyId,
                statusComboBox.getSelectedItem().toString()
            );
            
            if (rentFormStatus == "Register") {
                rentalController.addRental(rental);
            } else {
                rental.setId(1);
                rentalController.updateRental(rental);
            }
            
            updateTable();
            rentalsPanel.setVisible(true);
            rentalFormPanel.setVisible(false);
            
            JOptionPane.showMessageDialog(null, "Aluguel cadastrado com sucesso");
        } catch(Exception e) {
            System.out.println("Error: " + e);
        }
    }//GEN-LAST:event_submitRentButtonActionPerformed

    public void openUpdateForm(int id) {
        rentalsPanel.setVisible(false);
        rentalFormPanel.setVisible(true);
        rentFormStatus = "Update";
        
        RentalModel rental = rentalController.getRentalById(id);
        contractDateTextField.setText(rental.getContractDate());
        paymentBaseDateTextField.setText(String.valueOf(rental.getPaymentBaseDate()));
        rentValueTextField.setText(String.valueOf(rental.getRentValue()));
        landLordNameTextField.setText(rental.getLandlordName());
        landLordCPFTextField.setText(rental.getLandlordCpf());
        landLordPhoneTextField.setText(rental.getLandlordPhone());
        landLordEmailTextField.setText(rental.getLandlordEmail());
        tenantNameTextField.setText(rental.getTenantName());
        tenantCPFTextField.setText(rental.getTenantCpf());
        tenantPhoneTextField.setText(rental.getTenantPhone());
        tenantEmailTextField.setText(rental.getTenantEmail());
        durationTextField.setText(String.valueOf(rental.getDurationMonths()));
        statusComboBox.setSelectedItem(rental.getStatus());
    }
    
    public void updateTable() {
        String[] columnNames = {"ID", "Data", "Vencimento", "Status", "Editar", "Aluguel"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0)  {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 4 || column == 5;
            }
        };
        
        for (RentalModel rental : rentalController.getAllRentals()) {
            Object[] row = {
                rental.getId(),
                rental.getContractDate(),
                rental.getDueDate(),
                rental.getStatus(),
                "",
                "",
            };
            tableModel.addRow(row);
        }
        
        rentTable.setModel(tableModel);
        
        rentTable.getColumn("Editar").setCellRenderer(new RentalButtonRenderer());
        rentTable.getColumn("Editar").setCellEditor(new RentalButtonEditor(new JCheckBox(), rentTable, this));
        
        rentTable.getColumn("Aluguel").setCellRenderer(new PaymentButtonRenderer());
        rentTable.getColumn("Aluguel").setCellEditor(new PaymentButtonEditor(new JCheckBox(), rentTable));
        
        int[] preferredWidths = {40, 100, 100, 80, 40, 40};
        for (int i = 0; i < preferredWidths.length; i++) {
            rentTable.getColumnModel().getColumn(i).setPreferredWidth(preferredWidths[i]);
        }
    }
    
    private boolean isValidInteger(String input) {
        try {
            Integer.parseInt(input);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }
    
    private boolean isValidDouble(String input) {
        try {
            Double.parseDouble(input);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }


    public static String addMonthsToDate(String dateStr, int monthsToAdd) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate date = LocalDate.parse(dateStr, formatter);
        LocalDate updatedDate = date.plusMonths(monthsToAdd);
        return updatedDate.format(formatter);
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(int id, String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealEstate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealEstate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealEstate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealEstate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealEstate(id).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JPanel addressPanel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField areaTextField;
    private javax.swing.JComboBox<String> bathroomsComboBox;
    private javax.swing.JPanel bottomMenuPanel;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JButton closeRentFormButton;
    private javax.swing.JFormattedTextField contractDateTextField;
    private javax.swing.JPanel contractPane;
    private javax.swing.JButton deleteButton;
    private javax.swing.JFormattedTextField durationTextField;
    private javax.swing.JComboBox<String> garageComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField landLordCPFTextField;
    private javax.swing.JTextField landLordEmailTextField;
    private javax.swing.JTextField landLordNameTextField;
    private javax.swing.JPanel landLordPanel;
    private javax.swing.JTextField landLordPhoneTextField;
    private javax.swing.JTextField neighborhoodTextField;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JButton openRentFormButton;
    private javax.swing.JFormattedTextField paymentBaseDateTextField;
    private javax.swing.JPanel peoplePanel;
    private javax.swing.JPanel propertyPanel;
    private javax.swing.JPanel realEstatePanel;
    private javax.swing.JPanel rentOptionsPanel;
    private javax.swing.JTable rentTable;
    private javax.swing.JFormattedTextField rentValueTextField;
    private javax.swing.JPanel rentalFormPanel;
    private javax.swing.JPanel rentalPanel;
    private javax.swing.JPanel rentalsPanel;
    private javax.swing.JButton returnButton;
    private javax.swing.JComboBox<String> roomsComboBox;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JButton submitRentButton;
    private javax.swing.JTextField tenantCPFTextField;
    private javax.swing.JTextField tenantEmailTextField;
    private javax.swing.JTextField tenantNameTextField;
    private javax.swing.JPanel tenantPanel;
    private javax.swing.JTextField tenantPhoneTextField;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JTextField valueTextField;
    // End of variables declaration//GEN-END:variables
}

class RentalButtonRenderer extends JButton implements TableCellRenderer {
    public RentalButtonRenderer() {
        setToolTipText("Editar");

        ImageIcon pencilIcon = new ImageIcon(getClass().getResource("/static/icons/edit.png"));
        setIcon(pencilIcon);

        setText("");

        setHorizontalAlignment(SwingConstants.CENTER);
        setBorderPainted(false);
        setContentAreaFilled(false);
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
        boolean isSelected, boolean hasFocus, int row, int column) {
        return this;
    }
}

class PaymentButtonRenderer extends JButton implements TableCellRenderer {
    public PaymentButtonRenderer() {
        setToolTipText("Editar");

        ImageIcon pencilIcon = new ImageIcon(getClass().getResource("/static/icons/wallet.png"));
        setIcon(pencilIcon);

        setText("");

        setHorizontalAlignment(SwingConstants.CENTER);
        setBorderPainted(false);
        setContentAreaFilled(false);
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
        boolean isSelected, boolean hasFocus, int row, int column) {
        return this;
    }
}

class RentalButtonEditor extends DefaultCellEditor {
    private JButton button;
    private boolean isPushed;
    private JTable table;
    private JFrame mainFrame;

    public RentalButtonEditor(JCheckBox checkBox, JTable table, JFrame mainFrame) {
        super(checkBox);
        this.table = table;
        this.mainFrame = mainFrame;
        button = new JButton("");
        button.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                fireEditingStopped();
                int selectedRow = table.getSelectedRow();
                Object idValue = table.getValueAt(selectedRow, 0);
                openDetailsWindow(idValue);
            }
        });
    }

    @Override
    public Component getTableCellEditorComponent(JTable table, Object value,
        boolean isSelected, int row, int column) {
        isPushed = true;
        return button;
    }

    @Override
    public boolean stopCellEditing() {
        isPushed = false;
        return super.stopCellEditing();
    }

    private void openDetailsWindow(Object idObj) {
        int id = Integer.parseInt(idObj.toString());
        
        if (mainFrame instanceof RealEstate) {
            ((RealEstate) mainFrame).openUpdateForm(id);
        }
    }
}

class PaymentButtonEditor extends DefaultCellEditor {
    private JButton button;
    private boolean isPushed;
    private JTable table;
    private PaymentRegister paymentRegisterFrame = null;

    public PaymentButtonEditor(JCheckBox checkBox, JTable table) {
        super(checkBox);
        this.table = table;
        button = new JButton("");
        button.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                fireEditingStopped();
                int selectedRow = table.getSelectedRow();
                Object idValue = table.getValueAt(selectedRow, 0);
                openDetailsWindow(idValue);
            }
        });
    }

    @Override
    public Component getTableCellEditorComponent(JTable table, Object value,
        boolean isSelected, int row, int column) {
        isPushed = true;
        return button;
    }

    @Override
    public boolean stopCellEditing() {
        isPushed = false;
        return super.stopCellEditing();
    }

    private void openDetailsWindow(Object idObj) {
        int id = Integer.parseInt(idObj.toString());
        
         if (paymentRegisterFrame == null || !paymentRegisterFrame.isDisplayable()) {
            paymentRegisterFrame = new PaymentRegister(id);
            paymentRegisterFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            paymentRegisterFrame.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    paymentRegisterFrame = null;
                }
            });
            
            paymentRegisterFrame.setVisible(true);
        } else {
            paymentRegisterFrame.toFront();
            paymentRegisterFrame.requestFocus();
            paymentRegisterFrame.setState(JFrame.NORMAL);
        }
    }
}
