/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.imobiliaria.views;

import java.awt.Color;
import javax.swing.JOptionPane;

import com.mycompany.imobiliaria.models.RealEstateModel;
import com.mycompany.imobiliaria.controllers.RealEstateController;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author user
 */
public class RealEstateFormRegister extends javax.swing.JFrame {
    private static final RealEstateController realEstateController = new RealEstateController();
    
    /**
     * Creates new form PropertyForm
     */
    public RealEstateFormRegister() {
        initComponents();
        
        setLayout(null);
        backgroundLabel.setBounds(0, 0, getWidth(), getHeight());
        
        
        Image backgroundImage = new ImageIcon(getClass().getResource("/static/icons/background.png")).getImage();
        Image scaledImage = backgroundImage.getScaledInstance(getWidth(), getHeight(), Image.SCALE_SMOOTH);
  
        backgroundLabel.setIcon(new ImageIcon(scaledImage));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPanel = new javax.swing.JPanel();
        addressPanel = new javax.swing.JPanel();
        addressColumn1Panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        addressTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        neighborhoodTextField = new javax.swing.JTextField();
        addressColumn2Panel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        numberTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cityTextField = new javax.swing.JTextField();
        propertyPanel = new javax.swing.JPanel();
        propertyColumn1Panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        typeComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        roomsComboBox = new javax.swing.JComboBox<>();
        propertyColumn2Panel = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        bathroomsComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        areaTextField = new javax.swing.JTextField();
        propertyColumn3Panel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        valueTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        garageComboBox = new javax.swing.JComboBox<>();
        bottomMenuPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        cleanButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar Imóvel");
        setMaximumSize(new java.awt.Dimension(700, 440));
        setMinimumSize(new java.awt.Dimension(700, 440));
        setPreferredSize(new java.awt.Dimension(700, 440));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setMaximumSize(new java.awt.Dimension(700, 410));
        backgroundPanel.setMinimumSize(new java.awt.Dimension(700, 410));
        backgroundPanel.setPreferredSize(new java.awt.Dimension(700, 410));
        backgroundPanel.setBackground(new java.awt.Color(40, 40, 40, 160));
        backgroundPanel.setBorder(null);
        backgroundPanel.setLayout(new javax.swing.BoxLayout(backgroundPanel, javax.swing.BoxLayout.PAGE_AXIS));

        addressPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 25, 0, 25));
        addressPanel.setOpaque(false);
        addressPanel.setLayout(new java.awt.GridLayout(1, 2, 25, 0));

        addressColumn1Panel.setOpaque(false);
        addressColumn1Panel.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jLabel1.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Endereço:");
        addressColumn1Panel.add(jLabel1);

        addressTextField.setBackground(new java.awt.Color(120, 120, 120));
        addressTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        addressTextField.setForeground(new java.awt.Color(255, 255, 255));
        addressTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addressColumn1Panel.add(addressTextField);

        jLabel2.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bairro");
        addressColumn1Panel.add(jLabel2);

        neighborhoodTextField.setBackground(new java.awt.Color(120, 120, 120));
        neighborhoodTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        neighborhoodTextField.setForeground(new java.awt.Color(255, 255, 255));
        neighborhoodTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addressColumn1Panel.add(neighborhoodTextField);

        addressPanel.add(addressColumn1Panel);

        addressColumn2Panel.setOpaque(false);
        addressColumn2Panel.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jLabel3.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Número:");
        addressColumn2Panel.add(jLabel3);

        numberTextField.setBackground(new java.awt.Color(120, 120, 120));
        numberTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        numberTextField.setForeground(new java.awt.Color(255, 255, 255));
        numberTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addressColumn2Panel.add(numberTextField);

        jLabel4.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cidade");
        addressColumn2Panel.add(jLabel4);

        cityTextField.setBackground(new java.awt.Color(120, 120, 120));
        cityTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        cityTextField.setForeground(new java.awt.Color(255, 255, 255));
        cityTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addressColumn2Panel.add(cityTextField);

        addressPanel.add(addressColumn2Panel);

        backgroundPanel.add(addressPanel);

        propertyPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 25, 25, 25));
        propertyPanel.setOpaque(false);
        propertyPanel.setLayout(new java.awt.GridLayout(1, 3, 25, 0));

        propertyColumn1Panel.setOpaque(false);
        propertyColumn1Panel.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jLabel5.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Tipo");
        propertyColumn1Panel.add(jLabel5);

        typeComboBox.setBackground(new java.awt.Color(120, 120, 120));
        typeComboBox.setEditable(true);
        typeComboBox.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        typeComboBox.setForeground(new java.awt.Color(255, 255, 255));
        typeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Casa", "Terreno", "Apartamento", "Chácara" }));
        typeComboBox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        typeComboBox.getEditor().getEditorComponent().setBackground(new java.awt.Color(120, 120, 120));
        typeComboBox.getEditor().getEditorComponent().setForeground(new java.awt.Color(255, 255, 255));
        ((javax.swing.JComponent) typeComboBox.getEditor().getEditorComponent()).setBorder(new javax.swing.border.EmptyBorder(0, 0, 0, 0));
        propertyColumn1Panel.add(typeComboBox);

        jLabel6.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Números de quartos");
        propertyColumn1Panel.add(jLabel6);

        roomsComboBox.setBackground(new java.awt.Color(120, 120, 120));
        roomsComboBox.setEditable(true);
        roomsComboBox.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        roomsComboBox.setForeground(new java.awt.Color(255, 255, 255));
        roomsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 Quartos", "1 Quarto", "2 Quartos", "3 Quartos", "+4 Quartos" }));
        roomsComboBox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        roomsComboBox.getEditor().getEditorComponent().setBackground(new java.awt.Color(120, 120, 120));
        roomsComboBox.getEditor().getEditorComponent().setForeground(new java.awt.Color(255, 255, 255));
        ((javax.swing.JComponent) roomsComboBox.getEditor().getEditorComponent()).setBorder(new javax.swing.border.EmptyBorder(0, 0, 0, 0));
        propertyColumn1Panel.add(roomsComboBox);

        propertyPanel.add(propertyColumn1Panel);

        propertyColumn2Panel.setOpaque(false);
        propertyColumn2Panel.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jLabel7.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Números de banheiros");
        propertyColumn2Panel.add(jLabel7);

        bathroomsComboBox.setBackground(new java.awt.Color(120, 120, 120));
        bathroomsComboBox.setEditable(true);
        bathroomsComboBox.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        bathroomsComboBox.setForeground(new java.awt.Color(255, 255, 255));
        bathroomsComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 Banheiros", "1 Banheiro", "2 Banheiros", "3 Banheiros", "+4 Banheiros" }));
        bathroomsComboBox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        bathroomsComboBox.getEditor().getEditorComponent().setBackground(new java.awt.Color(120, 120, 120));
        bathroomsComboBox.getEditor().getEditorComponent().setForeground(new java.awt.Color(255, 255, 255));
        ((javax.swing.JComponent) bathroomsComboBox.getEditor().getEditorComponent()).setBorder(new javax.swing.border.EmptyBorder(0, 0, 0, 0));
        propertyColumn2Panel.add(bathroomsComboBox);

        jLabel8.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Área do imovel");
        propertyColumn2Panel.add(jLabel8);

        areaTextField.setBackground(new java.awt.Color(120, 120, 120));
        areaTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        areaTextField.setForeground(new java.awt.Color(255, 255, 255));
        areaTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        propertyColumn2Panel.add(areaTextField);

        propertyPanel.add(propertyColumn2Panel);

        propertyColumn3Panel.setOpaque(false);
        propertyColumn3Panel.setLayout(new java.awt.GridLayout(4, 1, 0, 5));

        jLabel9.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Valor");
        propertyColumn3Panel.add(jLabel9);

        valueTextField.setBackground(new java.awt.Color(120, 120, 120));
        valueTextField.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        valueTextField.setForeground(new java.awt.Color(255, 255, 255));
        valueTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        propertyColumn3Panel.add(valueTextField);

        jLabel10.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Garagem");
        propertyColumn3Panel.add(jLabel10);

        garageComboBox.setBackground(new java.awt.Color(120, 120, 120));
        garageComboBox.setEditable(true);
        garageComboBox.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        garageComboBox.setForeground(new java.awt.Color(255, 255, 255));
        garageComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não", "1 Carro", "2 Carros", "3 Carros", "+4 Carros" }));
        garageComboBox.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        garageComboBox.getEditor().getEditorComponent().setBackground(new java.awt.Color(120, 120, 120));
        garageComboBox.getEditor().getEditorComponent().setForeground(new java.awt.Color(255, 255, 255));
        ((javax.swing.JComponent) garageComboBox.getEditor().getEditorComponent()).setBorder(new javax.swing.border.EmptyBorder(0, 0, 0, 0));
        propertyColumn3Panel.add(garageComboBox);

        propertyPanel.add(propertyColumn3Panel);

        backgroundPanel.add(propertyPanel);

        bottomMenuPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        bottomMenuPanel.setMaximumSize(new java.awt.Dimension(32767, 100));
        bottomMenuPanel.setOpaque(false);
        bottomMenuPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 25, 5));

        cancelButton.setBackground(new java.awt.Color(40, 40, 80));
        cancelButton.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancelar");
        cancelButton.setPreferredSize(new java.awt.Dimension(150, 30));
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        bottomMenuPanel.add(cancelButton);

        cleanButton.setBackground(new java.awt.Color(40, 40, 80));
        cleanButton.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        cleanButton.setForeground(new java.awt.Color(255, 255, 255));
        cleanButton.setText("Limpar");
        cleanButton.setPreferredSize(new java.awt.Dimension(150, 30));
        cleanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanButtonActionPerformed(evt);
            }
        });
        bottomMenuPanel.add(cleanButton);

        saveButton.setBackground(new java.awt.Color(40, 40, 80));
        saveButton.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        saveButton.setForeground(new java.awt.Color(255, 255, 255));
        saveButton.setText("Salvar");
        saveButton.setPreferredSize(new java.awt.Dimension(150, 30));
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        bottomMenuPanel.add(saveButton);

        backgroundPanel.add(bottomMenuPanel);

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        backgroundLabel.setMaximumSize(new java.awt.Dimension(0, 0));
        backgroundLabel.setMinimumSize(new java.awt.Dimension(0, 0));
        backgroundLabel.setPreferredSize(new java.awt.Dimension(0, 0));
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 6, 1820, 1100));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        try {
            addressTextField.setBackground(Color.WHITE);
            neighborhoodTextField.setBackground(Color.WHITE);
            cityTextField.setBackground(Color.WHITE);
            areaTextField.setBackground(Color.WHITE);
            valueTextField.setBackground(Color.WHITE);
            
            if (addressTextField.getText().length() == 0) {
                addressTextField.setBackground(Color.RED);
                addressTextField.setToolTipText("Campo obrigatório");
                System.out.println("Required field");
                return;
            }
            
            if (neighborhoodTextField.getText().length() == 0) {
                neighborhoodTextField.setBackground(Color.RED);
                neighborhoodTextField.setToolTipText("Campo obrigatório");
                System.out.println("Required field");
                return;
            }
            
            if (cityTextField.getText().length() == 0) {
                cityTextField.setBackground(Color.RED);
                cityTextField.setToolTipText("Campo obrigatório");
                System.out.println("Required field");
                return;
            }
            
            if (!isValidDouble(areaTextField.getText().replace(",", "."))) {
                areaTextField.setBackground(Color.RED);
                areaTextField.setToolTipText("Valor invalido, formato: 0,00");
                System.out.println("Invalid area value");
                return;
            }
            
            if (!isValidDouble(valueTextField.getText().replace(",", "."))) {
                valueTextField.setBackground(Color.RED);
                valueTextField.setToolTipText("Valor invalido, formato: 0,00");
                System.out.println("Invalid value");
                return;
            }
            
            RealEstateModel realEstate = new RealEstateModel(
                addressTextField.getText(),
                neighborhoodTextField.getText(),
                numberTextField.getText(),
                cityTextField.getText(),
                typeComboBox.getSelectedItem().toString(),
                roomsComboBox.getSelectedIndex(),
                bathroomsComboBox.getSelectedIndex(),
                Double.valueOf(areaTextField.getText().replace(",", ".")),
                Double.valueOf(valueTextField.getText().replace(",", ".")),
                garageComboBox.getSelectedIndex()
            );
            
            realEstateController.addProperty(realEstate);
            
            JOptionPane.showMessageDialog(null, "Imóvel cadastrado com sucesso");
            dispose();
        } catch(Exception e) {
            System.out.println("Error: " + e);
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void cleanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanButtonActionPerformed
        addressTextField.setText("");
        numberTextField.setText("");
        neighborhoodTextField.setText("");
        cityTextField.setText("");
        areaTextField.setText("");
        valueTextField.setText("");
        typeComboBox.setSelectedIndex(0);
        roomsComboBox.setSelectedIndex(0);
        bathroomsComboBox.setSelectedIndex(0);
        garageComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_cleanButtonActionPerformed

    private boolean isValidDouble(String input) {
        try {
            Double.parseDouble(input);
            return true;
        } catch (NumberFormatException e) {
            return false;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealEstateFormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealEstateFormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealEstateFormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealEstateFormRegister.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealEstateFormRegister().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addressColumn1Panel;
    private javax.swing.JPanel addressColumn2Panel;
    private javax.swing.JPanel addressPanel;
    private javax.swing.JTextField addressTextField;
    private javax.swing.JTextField areaTextField;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JComboBox<String> bathroomsComboBox;
    private javax.swing.JPanel bottomMenuPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField cityTextField;
    private javax.swing.JButton cleanButton;
    private javax.swing.JComboBox<String> garageComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField neighborhoodTextField;
    private javax.swing.JTextField numberTextField;
    private javax.swing.JPanel propertyColumn1Panel;
    private javax.swing.JPanel propertyColumn2Panel;
    private javax.swing.JPanel propertyColumn3Panel;
    private javax.swing.JPanel propertyPanel;
    private javax.swing.JComboBox<String> roomsComboBox;
    private javax.swing.JButton saveButton;
    private javax.swing.JComboBox<String> typeComboBox;
    private javax.swing.JTextField valueTextField;
    // End of variables declaration//GEN-END:variables
}
