/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.imobiliaria.views;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

import com.mycompany.imobiliaria.controllers.RealEstateController;
import com.mycompany.imobiliaria.controllers.RentalController;
import com.mycompany.imobiliaria.models.RealEstateModel;
import com.mycompany.imobiliaria.models.RentalModel;
import com.mycompany.imobiliaria.dao.InitDatabase;

import java.awt.Component;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author user
 */
public class RealEstates extends javax.swing.JFrame {
    private static JFrame propertyRegisterFrame = null;
    private static final RealEstateController realEstateController = new RealEstateController();
    private static final RentalController rentalController = new RentalController();
    private int orderField = 0;
    private int orderDirection = 0;
    private String selection = "All";
    private Image backgroundImage = new ImageIcon(getClass().getResource("/static/icons/background.png")).getImage();

    
    /**
     * Creates new form RealEstates
     */
    public RealEstates() {
        new InitDatabase();
        
        initComponents();
        
        propertiesTable.getColumn("Ações").setCellRenderer(new PropertyButtonRenderer());
        propertiesTable.getColumn("Ações").setCellEditor(new PropertyButtonEditor(new JCheckBox(), propertiesTable, this));
        
        setLayout(null);
        backgroundLabel.setBounds(0, 0, getWidth(), getHeight());
        backgroundPanel.setBounds(0, 0, getWidth(), getHeight() - 30);

        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rentedFilterButtonGroup = new javax.swing.ButtonGroup();
        backgroundPanel = new javax.swing.JPanel();
        filtersPanel = new javax.swing.JPanel();
        orderPanel = new javax.swing.JPanel();
        orderLabel = new javax.swing.JLabel();
        orderFieldPanel = new javax.swing.JPanel();
        orderFieldComboBox = new javax.swing.JComboBox<>();
        orderDirectionComboBox = new javax.swing.JComboBox<>();
        selectLabel = new javax.swing.JLabel();
        rentedFilterPanel = new javax.swing.JPanel();
        selectAllRadioButton = new javax.swing.JRadioButton();
        selectRentedRadioButton = new javax.swing.JRadioButton();
        selectFreeRadioButton = new javax.swing.JRadioButton();
        searchPanel = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        alertPanel = new javax.swing.JPanel();
        alertButtonPanel = new javax.swing.JPanel();
        alertButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        propertiesScrollPanel = new javax.swing.JScrollPane();
        propertiesTable = new javax.swing.JTable();
        menuPanel = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();
        backgroundLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("imobiliária");
        setFont(new java.awt.Font("Nimbus Sans L", 0, 14)); // NOI18N
        setMinimumSize(new java.awt.Dimension(900, 500));
        setPreferredSize(new java.awt.Dimension(1200, 650));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPanel.setMinimumSize(new java.awt.Dimension(900, 500));
        backgroundPanel.setBackground(new java.awt.Color(40, 40, 40, 160));
        backgroundPanel.setBorder(null);
        backgroundPanel.setLayout(new javax.swing.BoxLayout(backgroundPanel, javax.swing.BoxLayout.PAGE_AXIS));

        filtersPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 0));
        filtersPanel.setMaximumSize(new java.awt.Dimension(33603, 100));
        filtersPanel.setMinimumSize(new java.awt.Dimension(700, 100));
        filtersPanel.setOpaque(false);
        filtersPanel.setPreferredSize(new java.awt.Dimension(700, 100));
        filtersPanel.setLayout(new javax.swing.BoxLayout(filtersPanel, javax.swing.BoxLayout.LINE_AXIS));

        orderPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 25, 0, 50));
        orderPanel.setOpaque(false);
        orderPanel.setLayout(new javax.swing.BoxLayout(orderPanel, javax.swing.BoxLayout.LINE_AXIS));

        orderLabel.setBackground(new java.awt.Color(0, 0, 0));
        orderLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        orderLabel.setForeground(new java.awt.Color(255, 255, 255));
        orderLabel.setText("Ordenar por: ");
        orderLabel.setToolTipText("");
        orderPanel.add(orderLabel);

        orderFieldPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        orderFieldPanel.setOpaque(false);
        orderFieldPanel.setLayout(new javax.swing.BoxLayout(orderFieldPanel, javax.swing.BoxLayout.LINE_AXIS));

        orderFieldComboBox.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        orderFieldComboBox.setForeground(new java.awt.Color(255, 255, 255));
        orderFieldComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Endereço", "Bairro", "Número", "Cidade", "Tipo", "Quartos", "Banheiros", "Área", "Valor", "Garagem" }));
        orderFieldComboBox.setToolTipText("");
        orderFieldComboBox.setMaximumSize(new java.awt.Dimension(150, 30));
        orderFieldComboBox.setMinimumSize(new java.awt.Dimension(150, 30));
        orderFieldComboBox.setPreferredSize(new java.awt.Dimension(150, 30));
        orderFieldComboBox.setBackground(new java.awt.Color(220, 220, 220, 80));
        orderFieldComboBox.setBorder(null);
        orderFieldPanel.add(orderFieldComboBox);

        orderPanel.add(orderFieldPanel);

        orderDirectionComboBox.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        orderDirectionComboBox.setForeground(new java.awt.Color(255, 255, 255));
        orderDirectionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crescente", "Decrescente" }));
        orderDirectionComboBox.setToolTipText("");
        orderDirectionComboBox.setLightWeightPopupEnabled(false);
        orderDirectionComboBox.setMaximumSize(new java.awt.Dimension(150, 30));
        orderDirectionComboBox.setMinimumSize(new java.awt.Dimension(150, 30));
        orderDirectionComboBox.setBackground(new java.awt.Color(220, 220, 220, 80));
        orderDirectionComboBox.setBorder(null);
        orderPanel.add(orderDirectionComboBox);

        filtersPanel.add(orderPanel);

        selectLabel.setBackground(new java.awt.Color(0, 0, 0));
        selectLabel.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        selectLabel.setForeground(new java.awt.Color(255, 255, 255));
        selectLabel.setText("Selicionar Imóveis");
        selectLabel.setToolTipText("");
        filtersPanel.add(selectLabel);

        rentedFilterPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 50));
        rentedFilterPanel.setOpaque(false);
        rentedFilterPanel.setLayout(new javax.swing.BoxLayout(rentedFilterPanel, javax.swing.BoxLayout.PAGE_AXIS));

        rentedFilterButtonGroup.add(selectAllRadioButton);
        selectAllRadioButton.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        selectAllRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        selectAllRadioButton.setSelected(true);
        selectAllRadioButton.setText("Todos");
        selectAllRadioButton.setToolTipText("");
        selectAllRadioButton.setContentAreaFilled(false);
        rentedFilterPanel.add(selectAllRadioButton);

        rentedFilterButtonGroup.add(selectRentedRadioButton);
        selectRentedRadioButton.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        selectRentedRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        selectRentedRadioButton.setText("Alugados");
        selectRentedRadioButton.setToolTipText("");
        selectRentedRadioButton.setContentAreaFilled(false);
        rentedFilterPanel.add(selectRentedRadioButton);

        rentedFilterButtonGroup.add(selectFreeRadioButton);
        selectFreeRadioButton.setFont(new java.awt.Font("Abyssinica SIL", 0, 14)); // NOI18N
        selectFreeRadioButton.setForeground(new java.awt.Color(255, 255, 255));
        selectFreeRadioButton.setText("Livres");
        selectFreeRadioButton.setToolTipText("");
        selectFreeRadioButton.setContentAreaFilled(false);
        rentedFilterPanel.add(selectFreeRadioButton);

        filtersPanel.add(rentedFilterPanel);

        searchPanel.setBackground(new java.awt.Color(200, 200, 200, 200));
        searchPanel.setBorder(null);
        searchPanel.setMaximumSize(new java.awt.Dimension(36, 36));
        searchPanel.setMinimumSize(new java.awt.Dimension(36, 36));
        searchPanel.setPreferredSize(new java.awt.Dimension(36, 36));
        searchPanel.setLayout(new java.awt.BorderLayout());

        searchButton.setBackground(new java.awt.Color(204, 204, 204));
        searchButton.setForeground(new java.awt.Color(0, 0, 0));
        searchButton.setAlignmentY(0.0F);
        searchButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        searchButton.setMaximumSize(new java.awt.Dimension(36, 36));
        searchButton.setMinimumSize(new java.awt.Dimension(36, 36));
        searchButton.setPreferredSize(new java.awt.Dimension(36, 36));
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        searchPanel.add(searchButton, java.awt.BorderLayout.CENTER);
        searchButton.setToolTipText("Filtrar imóveis");
        ImageIcon searchIcon = new ImageIcon(getClass().getResource("/static/icons/search.png"));
        searchButton.setIcon(searchIcon);
        searchButton.setText("");
        searchButton.setHorizontalAlignment(SwingConstants.CENTER);
        searchButton.setBorderPainted(false);
        searchButton.setContentAreaFilled(false);
        searchButton.setBorderPainted(true);

        filtersPanel.add(searchPanel);
        filtersPanel.add(filler1);

        alertPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 50));
        alertPanel.setOpaque(false);
        alertPanel.setLayout(new javax.swing.BoxLayout(alertPanel, javax.swing.BoxLayout.LINE_AXIS));

        alertButtonPanel.setMaximumSize(new java.awt.Dimension(36, 36));
        alertButtonPanel.setBackground(new java.awt.Color(200, 200, 200, 200));
        alertButtonPanel.setBorder(null);
        alertButtonPanel.setLayout(new java.awt.BorderLayout());

        alertButton.setBackground(new java.awt.Color(204, 204, 204));
        alertButton.setForeground(new java.awt.Color(0, 0, 0));
        alertButton.setBorderPainted(false);
        alertButton.setMaximumSize(new java.awt.Dimension(36, 36));
        alertButton.setMinimumSize(new java.awt.Dimension(36, 36));
        alertButton.setPreferredSize(new java.awt.Dimension(36, 36));
        alertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertButtonActionPerformed(evt);
            }
        });
        alertButtonPanel.add(alertButton, java.awt.BorderLayout.CENTER);
        alertButton.setToolTipText("Alugueis próximos do vencimento");
        ImageIcon scheduleIcon = new ImageIcon(getClass().getResource("/static/icons/schedule.png"));
        alertButton.setIcon(scheduleIcon);
        alertButton.setText("");
        alertButton.setHorizontalAlignment(SwingConstants.CENTER);
        alertButton.setBorderPainted(false);
        alertButton.setContentAreaFilled(false);
        alertButton.setBorderPainted(true);

        alertPanel.add(alertButtonPanel);

        filtersPanel.add(alertPanel);

        backgroundPanel.add(filtersPanel);

        contentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 25, 0, 25));
        contentPanel.setOpaque(false);
        contentPanel.setPreferredSize(new java.awt.Dimension(506, 760));
        contentPanel.setLayout(new java.awt.BorderLayout());

        propertiesScrollPanel.setOpaque(false);
        propertiesScrollPanel.getViewport().setBackground(new java.awt.Color(40, 40, 40, 180));
        propertiesScrollPanel.getViewport().setBorder(null);

        propertiesTable.setFont(new java.awt.Font("Abyssinica SIL", 0, 16)); // NOI18N
        propertiesTable.setForeground(new java.awt.Color(255, 255, 255));
        propertiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Endereço", "Bairro", "Número", "Cidade", "Tipo", "Quartos", "Banheiros", "Área", "Valor", "Garagem", "Alugado", "Vencimento", "Ações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        propertiesTable.setRowHeight(25);
        propertiesTable.getTableHeader().setReorderingAllowed(false);
        propertiesTable.setOpaque(false);
        ((DefaultTableCellRenderer) propertiesTable.getDefaultRenderer(Object.class)).setBackground(new java.awt.Color(120, 120, 160, 180));
        ((DefaultTableCellRenderer) propertiesTable.getDefaultRenderer(Object.class)).setBorder(null);
        propertiesTable.getTableHeader().setFont(new java.awt.Font("Abyssinica SIL", 0, 18)); // NOI18N
        propertiesTable.getTableHeader().setForeground(new java.awt.Color(255, 255, 255));
        propertiesTable.getTableHeader().setBackground(new java.awt.Color(40, 40, 80, 255));
        propertiesTable.getTableHeader().setBorder(null);
        propertiesScrollPanel.setViewportView(propertiesTable);
        if (propertiesTable.getColumnModel().getColumnCount() > 0) {
            propertiesTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            propertiesTable.getColumnModel().getColumn(1).setPreferredWidth(150);
            propertiesTable.getColumnModel().getColumn(2).setPreferredWidth(100);
            propertiesTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            propertiesTable.getColumnModel().getColumn(4).setPreferredWidth(100);
            propertiesTable.getColumnModel().getColumn(5).setPreferredWidth(60);
            propertiesTable.getColumnModel().getColumn(6).setPreferredWidth(60);
            propertiesTable.getColumnModel().getColumn(7).setPreferredWidth(60);
            propertiesTable.getColumnModel().getColumn(8).setPreferredWidth(60);
            propertiesTable.getColumnModel().getColumn(9).setPreferredWidth(60);
            propertiesTable.getColumnModel().getColumn(10).setPreferredWidth(60);
            propertiesTable.getColumnModel().getColumn(11).setPreferredWidth(60);
            propertiesTable.getColumnModel().getColumn(12).setPreferredWidth(80);
        }

        contentPanel.add(propertiesScrollPanel, java.awt.BorderLayout.CENTER);

        backgroundPanel.add(contentPanel);

        menuPanel.setMaximumSize(new java.awt.Dimension(32767, 60));
        menuPanel.setMinimumSize(new java.awt.Dimension(700, 60));
        menuPanel.setOpaque(false);
        menuPanel.setPreferredSize(new java.awt.Dimension(315, 60));

        updateButton.setBackground(new java.awt.Color(40, 40, 80));
        updateButton.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("Atualizar");
        updateButton.setMaximumSize(new java.awt.Dimension(150, 30));
        updateButton.setMinimumSize(new java.awt.Dimension(150, 30));
        updateButton.setPreferredSize(new java.awt.Dimension(150, 30));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        menuPanel.add(updateButton);

        registerButton.setBackground(new java.awt.Color(40, 40, 80));
        registerButton.setFont(new java.awt.Font("Abyssinica SIL", 1, 18)); // NOI18N
        registerButton.setForeground(new java.awt.Color(255, 255, 255));
        registerButton.setText("Cadastrar");
        registerButton.setMaximumSize(new java.awt.Dimension(150, 30));
        registerButton.setMinimumSize(new java.awt.Dimension(150, 30));
        registerButton.setPreferredSize(new java.awt.Dimension(150, 30));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        menuPanel.add(registerButton);

        backgroundPanel.add(menuPanel);

        getContentPane().add(backgroundPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 600));

        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/static/icons/background.png"))); // NOI18N
        backgroundLabel.setName("backgroundLabel"); // NOI18N
        Image scaledImage = backgroundImage.getScaledInstance(getWidth(), getHeight(), Image.SCALE_SMOOTH);
        backgroundLabel.setIcon(new ImageIcon(scaledImage));
        getContentPane().add(backgroundLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        this.orderField = orderFieldComboBox.getSelectedIndex();
        updateTable();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        if (propertyRegisterFrame == null || !propertyRegisterFrame.isDisplayable()) {
            propertyRegisterFrame = new RealEstateFormRegister();
            propertyRegisterFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            propertyRegisterFrame.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    updateTable();
                    propertyRegisterFrame = null;
                }
            });

            propertyRegisterFrame.setVisible(true);
        } else {
            propertyRegisterFrame.toFront();
            propertyRegisterFrame.requestFocus();
            propertyRegisterFrame.setState(JFrame.NORMAL);
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        this.orderField = orderFieldComboBox.getSelectedIndex();
        this.orderDirection = orderDirectionComboBox.getSelectedIndex();
        
        if (rentedFilterButtonGroup.getSelection() != null) {
            if (selectAllRadioButton.isSelected()) {
                this.selection = "All";
            } else if (selectRentedRadioButton.isSelected()) {
                this.selection = "Rented";
            } else {
                this.selection = "Free";
            }
        }
        
        updateTable();
    }//GEN-LAST:event_searchButtonActionPerformed

    private void alertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertButtonActionPerformed
        String[] columnNames = {"ID", "Endereço", "Bairro", "Número", "Cidade", "Tipo", "Quartos", "Banheiros", "Área", "Valor", "Garagem", "Alugado", "Vencimento", "Ações"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0)  {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 13;
            }
        };
        
        for (RentalModel rent : rentalController.getCloseDueDateRentals()) {
            RealEstateModel realEstate = realEstateController.getPropertyById(rent.getPropertyId());
    
                
            Object[] row = {
                realEstate.getId(),
                realEstate.getAddress(),
                realEstate.getNeighborhood(),
                realEstate.getNumber(),
                realEstate.getCity(),
                realEstate.getType(),
                realEstate.getRooms(),
                realEstate.getBathrooms(),
                realEstate.getArea(),
                realEstate.getValue(),
                realEstate.getGarage(),
                "Sim",
                String.format("%02d/%04d", rent.getDueMonth(), rent.getDueYear()),
                ""
            };
            tableModel.addRow(row);
        }
        
        propertiesTable.setModel(tableModel);
        propertiesTable.getColumn("Ações").setCellRenderer(new PropertyButtonRenderer());
        propertiesTable.getColumn("Ações").setCellEditor(new PropertyButtonEditor(new JCheckBox(), propertiesTable, this));
        
        int[] preferredWidths = {40, 200, 150, 70, 80, 50, 60, 60, 60, 80, 50, 50, 80, 120};
        for (int i = 0; i < preferredWidths.length; i++) {
            propertiesTable.getColumnModel().getColumn(i).setPreferredWidth(preferredWidths[i]);
        }
    }//GEN-LAST:event_alertButtonActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        Image scaledImage = backgroundImage.getScaledInstance(getWidth(), getHeight(), Image.SCALE_SMOOTH);
        backgroundLabel.setIcon(new ImageIcon(scaledImage));
        
        backgroundPanel.setBounds(0, 0, getWidth(), getHeight() - 30);
        backgroundLabel.setBounds(0, 0, getWidth(), getHeight());
        
        backgroundPanel.revalidate();
        backgroundPanel.repaint();
    }//GEN-LAST:event_formComponentResized

    public void updateTable() {
        DefaultTableModel tableModel = (DefaultTableModel) propertiesTable.getModel();
        tableModel.setRowCount(0);
        
        for (RealEstateModel realEstate : realEstateController.getAllProperties(this.orderField, this.orderDirection)) {
            RentalModel rent = rentalController.getLastActiveContract(realEstate.getId());
            String rentedProperty = (rent.getId() != 0) ? "Sim" : "Não";
            String dueDate = "";
            if (rent.getId() != 0) {
                if ("Free".equals(selection)) continue;
                dueDate =  String.format("%02d/%04d", rent.getDueMonth(), rent.getDueYear());
            } else {
                if ("Rented".equals(selection)) continue;
            }
                
            Object[] row = {
                realEstate.getId(),
                realEstate.getAddress(),
                realEstate.getNeighborhood(),
                realEstate.getNumber(),
                realEstate.getCity(),
                realEstate.getType(),
                realEstate.getRooms(),
                realEstate.getBathrooms(),
                realEstate.getArea(),
                realEstate.getValue(),
                realEstate.getGarage(),
                rentedProperty,
                dueDate,
                ""
            };
            tableModel.addRow(row);
        }
        
        propertiesTable.repaint();
        propertiesTable.getParent().repaint();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealEstates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealEstates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealEstates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealEstates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealEstates().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alertButton;
    private javax.swing.JPanel alertButtonPanel;
    private javax.swing.JPanel alertPanel;
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JPanel backgroundPanel;
    private javax.swing.JPanel contentPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel filtersPanel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JComboBox<String> orderDirectionComboBox;
    private javax.swing.JComboBox<String> orderFieldComboBox;
    private javax.swing.JPanel orderFieldPanel;
    private javax.swing.JLabel orderLabel;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JScrollPane propertiesScrollPanel;
    private javax.swing.JTable propertiesTable;
    private javax.swing.JButton registerButton;
    private javax.swing.ButtonGroup rentedFilterButtonGroup;
    private javax.swing.JPanel rentedFilterPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JRadioButton selectAllRadioButton;
    private javax.swing.JRadioButton selectFreeRadioButton;
    private javax.swing.JLabel selectLabel;
    private javax.swing.JRadioButton selectRentedRadioButton;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}

class PropertyButtonRenderer extends JButton implements TableCellRenderer {
    public PropertyButtonRenderer() {
        setToolTipText("Editar");

        ImageIcon pencilIcon = new ImageIcon(getClass().getResource("/static/icons/edit.png"));
        setIcon(pencilIcon);

        setText("");

        setHorizontalAlignment(SwingConstants.CENTER);
        setBorderPainted(false);
        setContentAreaFilled(false);
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
        boolean isSelected, boolean hasFocus, int row, int column) {
        return this;
    }
}

class PropertyButtonEditor extends DefaultCellEditor {
    
    private static RealEstate propertyUpdateFrame = null;
    private JButton button;
    private boolean isPushed;
    private JTable table;
    private JFrame mainFrame;

    public PropertyButtonEditor(JCheckBox checkBox, JTable table, JFrame mainFrame) {
        super(checkBox);
        this.table = table;
        this.mainFrame = mainFrame;
        button = new JButton("");
        button.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                fireEditingStopped();
                int selectedRow = table.getSelectedRow();
                Object idValue = table.getValueAt(selectedRow, 0);
                openDetailsWindow(idValue);
            }
        });
    }

    @Override
    public Component getTableCellEditorComponent(JTable table, Object value,
        boolean isSelected, int row, int column) {
        isPushed = true;
        return button;
    }

    @Override
    public boolean stopCellEditing() {
        isPushed = false;
        return super.stopCellEditing();
    }

    private void openDetailsWindow(Object idObj) {
        if (propertyUpdateFrame != null) {
            propertyUpdateFrame.dispose();
        }
        
        int id = Integer.parseInt(idObj.toString());
        propertyUpdateFrame = new RealEstate(id);
        propertyUpdateFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        propertyUpdateFrame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                if (mainFrame instanceof RealEstates) {
                    ((RealEstates) mainFrame).updateTable();
                }
            }
        });

        propertyUpdateFrame.setVisible(true);
    }
}
