/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.imobiliaria.views;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

import com.mycompany.imobiliaria.controllers.RealEstateController;
import com.mycompany.imobiliaria.controllers.RentalController;
import com.mycompany.imobiliaria.models.RealEstateModel;
import com.mycompany.imobiliaria.models.RentalModel;
import com.mycompany.imobiliaria.dao.InitDatabase;

import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.DefaultCellEditor;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author user
 */
public class RealEstates extends javax.swing.JFrame {
    private static JFrame propertyRegisterFrame = null;
    private static final RealEstateController realEstateController = new RealEstateController();
    private static final RentalController rentalController = new RentalController();
    private int orderField = 0;
    private int orderDirection = 0;
    private String selection = "All";
    
    
    /**
     * Creates new form RealEstates
     */
    public RealEstates() {
        new InitDatabase();
        
        initComponents();
        
        updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rentedFilterButtonGroup = new javax.swing.ButtonGroup();
        titlePanel = new javax.swing.JPanel();
        titleLabel = new javax.swing.JLabel();
        filtersPanel = new javax.swing.JPanel();
        orderPanel = new javax.swing.JPanel();
        orderLabel = new javax.swing.JLabel();
        orderFieldPanel = new javax.swing.JPanel();
        orderFieldComboBox = new javax.swing.JComboBox<>();
        orderDirectionComboBox = new javax.swing.JComboBox<>();
        selectLabel = new javax.swing.JLabel();
        rentedFilterPanel = new javax.swing.JPanel();
        selectAllRadioButton = new javax.swing.JRadioButton();
        selectRentedRadioButton = new javax.swing.JRadioButton();
        selectFreeRadioButton = new javax.swing.JRadioButton();
        searchButton = new javax.swing.JButton();
        contentPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        propertiesTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        updateButton = new javax.swing.JButton();
        registerButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("imobiliária");
        setFont(new java.awt.Font("Nimbus Sans L", 0, 14)); // NOI18N
        setMinimumSize(new java.awt.Dimension(700, 440));
        setPreferredSize(new java.awt.Dimension(1200, 600));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

        titleLabel.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        titleLabel.setText("Imóveis");
        titlePanel.add(titleLabel);

        getContentPane().add(titlePanel);

        filtersPanel.setLayout(new javax.swing.BoxLayout(filtersPanel, javax.swing.BoxLayout.LINE_AXIS));

        orderPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 50));
        orderPanel.setLayout(new javax.swing.BoxLayout(orderPanel, javax.swing.BoxLayout.LINE_AXIS));

        orderLabel.setText("Ordenar por: ");
        orderPanel.add(orderLabel);

        orderFieldPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        orderFieldPanel.setLayout(new javax.swing.BoxLayout(orderFieldPanel, javax.swing.BoxLayout.LINE_AXIS));

        orderFieldComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Endereço", "Bairro", "Número", "Cidade", "Tipo", "Quartos", "Banheiros", "Área", "Valor", "Garagem" }));
        orderFieldComboBox.setMaximumSize(new java.awt.Dimension(150, 30));
        orderFieldComboBox.setMinimumSize(new java.awt.Dimension(150, 30));
        orderFieldComboBox.setPreferredSize(new java.awt.Dimension(150, 30));
        orderFieldPanel.add(orderFieldComboBox);

        orderPanel.add(orderFieldPanel);

        orderDirectionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Crescente", "Decrescente" }));
        orderDirectionComboBox.setLightWeightPopupEnabled(false);
        orderDirectionComboBox.setMaximumSize(new java.awt.Dimension(150, 30));
        orderDirectionComboBox.setMinimumSize(new java.awt.Dimension(150, 30));
        orderPanel.add(orderDirectionComboBox);

        filtersPanel.add(orderPanel);

        selectLabel.setText("Selicionar Imóveis");
        filtersPanel.add(selectLabel);

        rentedFilterPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 50));
        rentedFilterPanel.setLayout(new javax.swing.BoxLayout(rentedFilterPanel, javax.swing.BoxLayout.PAGE_AXIS));

        rentedFilterButtonGroup.add(selectAllRadioButton);
        selectAllRadioButton.setSelected(true);
        selectAllRadioButton.setText("Todos");
        rentedFilterPanel.add(selectAllRadioButton);

        rentedFilterButtonGroup.add(selectRentedRadioButton);
        selectRentedRadioButton.setText("Alugados");
        rentedFilterPanel.add(selectRentedRadioButton);

        rentedFilterButtonGroup.add(selectFreeRadioButton);
        selectFreeRadioButton.setText("Livres");
        rentedFilterPanel.add(selectFreeRadioButton);

        filtersPanel.add(rentedFilterPanel);

        searchButton.setText("Pesquisar");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });
        filtersPanel.add(searchButton);

        getContentPane().add(filtersPanel);

        contentPanel.setLayout(new java.awt.BorderLayout());

        propertiesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Endereço", "Bairro", "Número", "Cidade", "Tipo", "Quartos", "Banheiros", "Área", "Valor", "Garagem", "Ações"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Byte.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(propertiesTable);

        contentPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);
        contentPanel.add(jPanel1, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(contentPanel);

        menuPanel.setOpaque(false);

        updateButton.setText("Atualizar");
        updateButton.setMaximumSize(new java.awt.Dimension(150, 30));
        updateButton.setMinimumSize(new java.awt.Dimension(150, 30));
        updateButton.setPreferredSize(new java.awt.Dimension(150, 30));
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });
        menuPanel.add(updateButton);

        registerButton.setText("Cadastrar");
        registerButton.setMaximumSize(new java.awt.Dimension(150, 30));
        registerButton.setMinimumSize(new java.awt.Dimension(150, 30));
        registerButton.setPreferredSize(new java.awt.Dimension(150, 30));
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });
        menuPanel.add(registerButton);

        getContentPane().add(menuPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        this.orderField = orderFieldComboBox.getSelectedIndex();
        updateTable();
    }//GEN-LAST:event_updateButtonActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        if (propertyRegisterFrame == null || !propertyRegisterFrame.isDisplayable()) {
            propertyRegisterFrame = new RealEstateFormRegister();
            propertyRegisterFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            propertyRegisterFrame.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosed(WindowEvent e) {
                    updateTable();
                    propertyRegisterFrame = null;
                }
            });

            propertyRegisterFrame.setVisible(true);
        } else {
            propertyRegisterFrame.toFront();
            propertyRegisterFrame.requestFocus();
            propertyRegisterFrame.setState(JFrame.NORMAL);
        }
    }//GEN-LAST:event_registerButtonActionPerformed

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        this.orderField = orderFieldComboBox.getSelectedIndex();
        this.orderDirection = orderDirectionComboBox.getSelectedIndex();
        
        if (rentedFilterButtonGroup.getSelection() != null) {
            if (selectAllRadioButton.isSelected()) {
                this.selection = "All";
            } else if (selectRentedRadioButton.isSelected()) {
                this.selection = "Rented";
            } else {
                this.selection = "Free";
            }
        }
        
        updateTable();
    }//GEN-LAST:event_searchButtonActionPerformed

    public void updateTable() {
        String[] columnNames = {"ID", "Endereço", "Bairro", "Número", "Cidade", "Tipo", "Quartos", "Banheiros", "Área", "Valor", "Garagem", "Alugado", "Vencimento", "Ações"};
        DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0)  {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 13;
            }
        };
        
        for (RealEstateModel realEstate : realEstateController.getAllProperties(this.orderField, this.orderDirection)) {
            RentalModel rent = rentalController.getLastActiveContract(realEstate.getId());
            String rentedProperty = (rent.getId() != 0) ? "Sim" : "Não";
            String dueDate = "";
            if (rent.getId() != 0) {
                if (selection == "Free") continue;
                dueDate =  String.format("%02d/%04d", rent.getDueMonth(), rent.getDueYear());
            } else {
                if (selection == "Rented") continue;
            }
                
            Object[] row = {
                realEstate.getId(),
                realEstate.getAddress(),
                realEstate.getNeighborhood(),
                realEstate.getNumber(),
                realEstate.getCity(),
                realEstate.getType(),
                realEstate.getRooms(),
                realEstate.getBathrooms(),
                realEstate.getArea(),
                realEstate.getValue(),
                realEstate.getGarage(),
                rentedProperty,
                dueDate,
                ""
            };
            tableModel.addRow(row);
        }
        
        propertiesTable.setModel(tableModel);
        propertiesTable.getColumn("Ações").setCellRenderer(new PropertyButtonRenderer());
        propertiesTable.getColumn("Ações").setCellEditor(new PropertyButtonEditor(new JCheckBox(), propertiesTable, this));
        
        int[] preferredWidths = {40, 200, 150, 70, 80, 50, 60, 60, 60, 80, 50, 50, 80, 120};
        for (int i = 0; i < preferredWidths.length; i++) {
            propertiesTable.getColumnModel().getColumn(i).setPreferredWidth(preferredWidths[i]);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RealEstates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RealEstates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RealEstates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RealEstates.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RealEstates().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel filtersPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JComboBox<String> orderDirectionComboBox;
    private javax.swing.JComboBox<String> orderFieldComboBox;
    private javax.swing.JPanel orderFieldPanel;
    private javax.swing.JLabel orderLabel;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JTable propertiesTable;
    private javax.swing.JButton registerButton;
    private javax.swing.ButtonGroup rentedFilterButtonGroup;
    private javax.swing.JPanel rentedFilterPanel;
    private javax.swing.JButton searchButton;
    private javax.swing.JRadioButton selectAllRadioButton;
    private javax.swing.JRadioButton selectFreeRadioButton;
    private javax.swing.JLabel selectLabel;
    private javax.swing.JRadioButton selectRentedRadioButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}

class PropertyButtonRenderer extends JButton implements TableCellRenderer {
    public PropertyButtonRenderer() {
        setToolTipText("Editar");

        ImageIcon pencilIcon = new ImageIcon(getClass().getResource("/static/icons/edit.png"));
        setIcon(pencilIcon);

        setText("");

        setHorizontalAlignment(SwingConstants.CENTER);
        setBorderPainted(false);
        setContentAreaFilled(false);
    }

    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,
        boolean isSelected, boolean hasFocus, int row, int column) {
        return this;
    }
}

class PropertyButtonEditor extends DefaultCellEditor {
    
    private static RealEstate propertyUpdateFrame = null;
    private JButton button;
    private boolean isPushed;
    private JTable table;
    private JFrame mainFrame;

    public PropertyButtonEditor(JCheckBox checkBox, JTable table, JFrame mainFrame) {
        super(checkBox);
        this.table = table;
        this.mainFrame = mainFrame;
        button = new JButton("");
        button.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                fireEditingStopped();
                int selectedRow = table.getSelectedRow();
                Object idValue = table.getValueAt(selectedRow, 0);
                openDetailsWindow(idValue);
            }
        });
    }

    @Override
    public Component getTableCellEditorComponent(JTable table, Object value,
        boolean isSelected, int row, int column) {
        isPushed = true;
        return button;
    }

    @Override
    public boolean stopCellEditing() {
        isPushed = false;
        return super.stopCellEditing();
    }

    private void openDetailsWindow(Object idObj) {
        if (propertyUpdateFrame != null) {
            propertyUpdateFrame.dispose();
        }
        
        int id = Integer.parseInt(idObj.toString());
        propertyUpdateFrame = new RealEstate(id);
        propertyUpdateFrame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        propertyUpdateFrame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                if (mainFrame instanceof RealEstates) {
                    ((RealEstates) mainFrame).updateTable();
                }
            }
        });

        propertyUpdateFrame.setVisible(true);
    }
}
